package cinesa;

import com.mysql.jdbc.PreparedStatement;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Paint;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saulg
 */
public class AdminOperaciones extends javax.swing.JFrame {

    /**
     * Creates new form Cine
     */
    Controlador con = new Controlador();
    PreparedStatement ps;
    Hora hr = new Hora();
    Font f = new Font("Franklin Gothic Demi Cond", Font.PLAIN, 18);
    boolean x = true;
    DefaultTableModel model = new DefaultTableModel();
    String user2;
    String ss;
    String tt;

    public AdminOperaciones(String user, String password) throws SQLException {
        setUndecorated(true);
        setSize(1200, 690);
        Shape forma = new RoundRectangle2D.Double(0, -0, getBounds().width, getBounds().height, 30, 30);
        setShape(forma);
        //this.pack();
        setLocationRelativeTo(null);
        setVisible(true);
        initComponents();
        jLabel1.setText("A");
        jLabel5.setText("Cuentas");
        hr.setTexto(jLabel7);
        hr.start();
        user2 = user;
        jLabel1.setText("Administrador: " + user);
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesNoSelect.png")));
        jButton6.setBackground(new Color(105, 252, 205));
        jLabel13.setIcon(new ImageIcon(getClass().getResource("/Images/BarraGris.png")));
        jButton6.setContentAreaFilled(false);
        jLabel9.setVisible(false);
        jLabel2.setVisible(false);
        jLabel15.setVisible(false);
        jRadioButton2.setVisible(false);
        jTextField2.setVisible(false);
        jPasswordField1.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jRadioButton1.setVisible(false);
        jLabel8.setVisible(false);
        jButton6.setVisible(false);
        jTable1.setVisible(false);
        jScrollPane1.setVisible(false);
        model.addColumn("Usuario");
        model.addColumn("Contraseña");
        model.addColumn("Email");
        model.addColumn("Nivel");
        model.addColumn("VIP");
        jTextField4.setVisible(false);
        jComboBox1.setVisible(false);
        jTextField4.setLocation(630, 220);
        jLabel13.setLocation(610, 210);
        jLabel11.setLocation(610, 280);
        jPasswordField1.setLocation(630, 290);
        jLabel10.setLocation(496, 46);
        jTextField3.setLocation(630, 360);

        jLabel18.setSize(496, 46);
        jLabel18.setLocation(610, 320);
        jLabel18.setVisible(false);
        jLabel12.setVisible(false);
        jLabel12.setLocation(630, 320);
        jLabel18.setIcon(new ImageIcon(getClass().getResource("/Images/BarraGris.png")));

        ss = user;
        tt = password;
    }

    private AdminOperaciones() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1037, 495));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 690));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 690));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 255));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(510, 490, 450, 40);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 0, 310, 40);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(660, 0, 240, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FondoSup.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, -530, 680, 580);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(430, 290, 180, 40);

        jButton1.setToolTipText("Buscar cuenta");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton1MouseWheelMoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(155, 175, 80, 80);

        jButton3.setToolTipText("Modificar cuenta");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton3MouseWheelMoved(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(253, 175, 80, 80);

        jButton4.setToolTipText("Borrar cuenta");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton4MouseWheelMoved(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(345, 175, 80, 80);

        jButton5.setToolTipText("Agregar cuenta");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton5MouseMoved(evt);
            }
        });
        jButton5.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton5MouseWheelMoved(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(60, 170, 85, 85);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cuentas");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 110, 1010, 40);

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Registrar");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(770, 545, 160, 40);

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Usuario");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(460, 220, 150, 40);

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Email");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(460, 360, 150, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1160, 430, 680, 600);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(-600, 270, 680, 600);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Boton2.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton6MouseMoved(evt);
            }
        });
        jButton6.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton6MouseWheelMoved(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(770, 520, 160, 95);

        jTextField3.setBackground(new java.awt.Color(242, 242, 242));
        jTextField3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(630, 360, 460, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BarraGris.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(610, 350, 496, 60);

        jPasswordField1.setBackground(new java.awt.Color(242, 242, 242));
        jPasswordField1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(630, 290, 460, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BarraGris.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(610, 280, 496, 60);

        jRadioButton1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(242, 242, 242));
        jRadioButton1.setText("Vendedor");
        jRadioButton1.setFocusPainted(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(920, 440, 230, 30);

        jRadioButton2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(242, 242, 242));
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Administrador");
        jRadioButton2.setFocusPainted(false);
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton2MousePressed(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(640, 440, 230, 30);

        jTable1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 22)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Contraseña", "Email", "Nivel", "VIP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(153, 153, 255));
        jTable1.setOpaque(false);
        jTable1.setRowHeight(28);
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 490, 220, 50);

        jTextField4.setBackground(new java.awt.Color(242, 242, 242));
        jTextField4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 51, 51));
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(630, 220, 460, 40);

        jTextField2.setBackground(new java.awt.Color(242, 242, 242));
        jTextField2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(630, 220, 460, 40);

        jComboBox1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Email", "Nivel", "VIP" }));
        jComboBox1.setBorder(null);
        jComboBox1.setLightWeightPopupEnabled(false);
        jComboBox1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jComboBox1InputMethodTextChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox1KeyReleased(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(950, 210, 140, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BarraGris.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(610, 210, 496, 60);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OperacionesNoSelect.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel4MouseMoved(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 60, 1080, 230);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(530, 546, 80, 20);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegresarB.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(58, 10, 90, 70);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CerrarP.png"))); // NOI18N
        jButton7.setToolTipText("Cerrar Aplicación");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(1110, 10, 70, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesNoSelect.png")));
        jButton6.setContentAreaFilled(false);
        jButton6.setIcon(new ImageIcon(getClass().getResource("/Images/Boton2.png")));
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesNoSelect.png")));
    }//GEN-LAST:event_jLabel4MouseMoved

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesSearch.png")));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseWheelMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel12.setVisible(false);
        jLabel18.setVisible(false);
        jLabel12.setText("");
        jTextField4.setText("");
        jPasswordField1.setText("");
        jTextField3.setText("");
        jLabel13.setIcon(new ImageIcon(getClass().getResource("/Images/BarraGrisS.png")));
        jLabel13.setLocation(580, 200);
        jTextField2.setVisible(false);
        jLabel9.setLocation(430, 210);
        jLabel9.setText("Buscar: ");
        jLabel2.setVisible(false);
        jPasswordField1.setVisible(false);
        jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField3.setVisible(false);
        jLabel15.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton1.setVisible(false);
        jLabel5.setText("Búsqueda de cuentas");
        jTable1.setVisible(true);
        //jTable1.setSize(800, 400);
        //jTable1.setLocation(100, 150);
        jScrollPane1.setVisible(true);
        jScrollPane1.setSize(1000, 290);
        jScrollPane1.setLocation(110, 305);
        jLabel13.setVisible(true);
        jLabel9.setVisible(true);
        jLabel8.setVisible(false);
        jButton6.setVisible(false);
        jTextField4.setVisible(true);
        jTextField4.setSize(250, 40);
        jTextField4.setLocation(600, 210);
        jComboBox1.setVisible(true);
        tabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesModify.png")));
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton3MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseWheelMoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel8.setVisible(true);
        jLabel8.setText("Modificar");
        jButton6.setLocation(770, 580);
        jLabel8.setLocation(770, 605);
        jLabel8.setVisible(true);
        jButton6.setVisible(true);
        jTextField4.setText("");
        jLabel12.setText("");
        jPasswordField1.setText("");
        jTextField3.setText("");
        jPasswordField1.setEditable(false);
        jTextField3.setEditable(false);
        jLabel13.setIcon(new ImageIcon(getClass().getResource("/Images/BarraGrisS.png")));
        jLabel13.setLocation(580, 200);
        jTextField2.setVisible(false);
        jLabel9.setLocation(430, 210);
        jLabel9.setText("Buscar: ");
        jLabel2.setVisible(false);
        jPasswordField1.setVisible(false);
        jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField3.setVisible(false);
        jLabel15.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton1.setVisible(false);
        jLabel5.setText("Modificar cuentas");
        jTable1.setVisible(true);
        //jTable1.setSize(800, 400);
        //jTable1.setLocation(100, 150);
        jScrollPane1.setVisible(true);
        jScrollPane1.setSize(450, 290);
        jScrollPane1.setLocation(110, 305);
        jLabel13.setVisible(true);
        jLabel9.setVisible(true);
        jTextField4.setVisible(true);
        jTextField4.setSize(250, 40);
        jTextField4.setLocation(600, 210);
        jComboBox1.setVisible(true);

        jLabel11.setVisible(true);
        jPasswordField1.setVisible(true);
        jTextField3.setVisible(true);
        jLabel10.setVisible(true);

        jLabel18.setVisible(true);
        jLabel11.setLocation(610, 380);
        jPasswordField1.setLocation(630, 390);
        jLabel10.setLocation(610, 450);
        jTextField3.setLocation(630, 460);
        jLabel12.setVisible(true);
        jRadioButton2.setVisible(true);
        jRadioButton2.setLocation(640, 530);
        jRadioButton1.setVisible(true);
        jRadioButton1.setLocation(920, 530);
        tabla();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesDelete.png")));
    }//GEN-LAST:event_jButton4MouseMoved

    private void jButton4MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton4MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseWheelMoved

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jLabel12.setVisible(false);
        jLabel18.setVisible(false);
        jLabel12.setText("");
        jTextField4.setText("");
        jPasswordField1.setText("");
        jTextField3.setText("");
        jLabel13.setIcon(new ImageIcon(getClass().getResource("/Images/BarraGrisS.png")));
        jLabel13.setLocation(580, 200);
        jTextField2.setVisible(false);
        jLabel9.setLocation(430, 210);
        jLabel9.setText("Buscar: ");
        jLabel2.setVisible(false);
        jPasswordField1.setVisible(false);
        jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jTextField3.setVisible(false);
        jLabel15.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton1.setVisible(false);
        jLabel5.setText("Borrar cuentas");
        jTable1.setVisible(true);
        //jTable1.setSize(800, 400);
        //jTable1.setLocation(100, 150);
        jScrollPane1.setVisible(true);
        jScrollPane1.setSize(1000, 230);
        jScrollPane1.setLocation(110, 305);
        jLabel13.setVisible(true);
        jLabel9.setVisible(true);
        jTextField4.setVisible(true);
        jTextField4.setSize(250, 40);
        jTextField4.setLocation(600, 210);
        jComboBox1.setVisible(true);
        jLabel8.setVisible(true);
        jLabel8.setText("Borrar");
        jButton6.setLocation(530, 570);
        jButton6.setVisible(true);
        jLabel8.setLocation(530, 595);
        tabla();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesAdd.png")));
    }//GEN-LAST:event_jButton5MouseMoved

    private void jButton5MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton5MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseWheelMoved

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jButton6.setLocation(770, 520);
        jLabel8.setLocation(770, 545);
        jLabel8.setText("Registrar");
        jTextField4.setText("");
        jLabel12.setText("");
        jPasswordField1.setText("");
        jTextField3.setText("");
        jPasswordField1.setEditable(true);
        jTextField3.setEditable(true);
        jLabel12.setVisible(false);
        jLabel18.setVisible(false);
        jLabel13.setLocation(610, 210);
        jTextField2.setLocation(630, 220);
        jLabel9.setLocation(460, 220);

        jLabel11.setLocation(610, 280);
        jPasswordField1.setLocation(630, 290);
        jLabel10.setLocation(610, 350);
        jTextField3.setLocation(630, 360);

        jLabel13.setIcon(new ImageIcon(getClass().getResource("/Images/BarraGris.png")));
        jLabel9.setVisible(true);
        jLabel2.setVisible(true);
        jLabel15.setVisible(true);
        jTextField2.setVisible(true);
        jPasswordField1.setVisible(true);
        jTextField3.setVisible(true);
        jLabel13.setVisible(true);
        jLabel11.setVisible(true);
        jLabel10.setVisible(true);
        jLabel8.setVisible(true);
        jButton6.setVisible(true);
        jRadioButton1.setVisible(true);
        jRadioButton2.setVisible(true);
        jLabel5.setText("Registro de cuentas");
        jLabel9.setText("Usuario");
        jLabel2.setText("Contraseña");
        jLabel15.setText("Email");
        jScrollPane1.setVisible(false);
        jTextField4.setVisible(false);
        jComboBox1.setVisible(false);
        jTextField4.setText("");
        jRadioButton2.setLocation(640, 440);
        jRadioButton1.setLocation(920, 440);
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton6MouseWheelMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton6MouseWheelMoved

    private void jButton6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseMoved
        // TODO add your handling code here:
        jButton6.setIcon(new ImageIcon(getClass().getResource("/Images/Boton1.png")));
    }//GEN-LAST:event_jButton6MouseMoved

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        if (("".equals(jTextField2.getText()) || "".equals(jTextField3.getText()) || "".equals(jPasswordField1.getText())) && "Registrar".equals(jLabel8.getText())) {
            UIManager.put("control", new Color(51, 51, 51));
            UIManager.put("OptionPane.messageFont", f);
            UIManager.put("OptionPane.messageForeground", Color.white);
            UIManager.put("OptionPane.messageIconImage", null);
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar.\nIntente nuevamente.");

        } else {
            if ("Registrar".equals(jLabel8.getText())) {
                String nivel = "";
                if (jRadioButton1.isSelected()) {
                    nivel = "V";
                } else {
                    if (jRadioButton2.isSelected()) {
                        nivel = "A";
                    }
                }
                try {
                    String g = "insert into cuentas (usuario, contraseña, email, nivel, VIP) values('" + jTextField2.getText() + "', '" + jPasswordField1.getText() + "', '" + jTextField3.getText() + "', '" + nivel + "', 'No')";
                    ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM cuentas");
                    ResultSet sr = ps.executeQuery();
                    while (sr.next()) {
                        String s = sr.getString("usuario");
                        String u = sr.getString("email");
                        System.out.println(s + u);
                        if (s.equals(jTextField2.getText()) || u.equals(jTextField3.getText())) {
                            UIManager.put("control", new Color(51, 51, 51));
                            UIManager.put("OptionPane.messageFont", f);
                            UIManager.put("OptionPane.messageForeground", Color.white);
                            UIManager.put("OptionPane.messageIconImage", null);
                            JOptionPane.showMessageDialog(null, "La cuenta y/o el email ingresados ya están en uso.\nIngrese de nuevo los datos.");

                            break;
                        } else {
                            ps = (PreparedStatement) con.getConect().prepareStatement(g);
                            ps.execute();
                            UIManager.put("control", new Color(51, 51, 51));
                            UIManager.put("OptionPane.messageFont", f);
                            UIManager.put("OptionPane.messageForeground", Color.white);
                            UIManager.put("OptionPane.messageIconImage", null);
                            JOptionPane.showMessageDialog(null, "La cuenta se ha registrado correctamente.");
                            jTextField2.setText("");
                            jTextField3.setText("");
                            jPasswordField1.setText("");
                            break;
                        }

                    }
                    ps.close();
                } catch (SQLException ex) {

                }
            } else {
                if ("Modificar".equals(jLabel8.getText())) {

                    String nivel = "";
                    if (jRadioButton1.isSelected()) {
                        nivel = "V";
                    } else {
                        if (jRadioButton2.isSelected()) {
                            nivel = "A";
                        }
                    }
                    try {
                        if (!"".equals(jPasswordField1.getText()) && !"".equals(jTextField3.getText())) {
                            if (!"Key".equals(jLabel12.getText())) {
                                String sql = "UPDATE cuentas SET contraseña='" + jPasswordField1.getText() + "', email='" + jTextField3.getText() + "', nivel='" + nivel + "' WHERE usuario='" + jLabel12.getText() + "'";
                                ps = (PreparedStatement) con.getConect().prepareStatement(sql);
                                ps.executeUpdate();
                                tabla();
                                jTextField4.setText("");
                                jLabel12.setText("");
                                jPasswordField1.setText("");
                                jTextField3.setText("");
                                jPasswordField1.setEditable(false);
                                jTextField3.setEditable(false);
                                UIManager.put("control", new Color(51, 51, 51));
                                UIManager.put("OptionPane.messageFont", f);
                                UIManager.put("OptionPane.messageForeground", Color.white);
                                UIManager.put("OptionPane.messageIconImage", null);
                                JOptionPane.showMessageDialog(null, "Se ha modificado la información de la cuenta.");
                            } else {
                                UIManager.put("control", new Color(51, 51, 51));
                                UIManager.put("OptionPane.messageFont", f);
                                UIManager.put("OptionPane.messageForeground", Color.white);
                                UIManager.put("OptionPane.messageIconImage", null);
                                JOptionPane.showMessageDialog(null, "No puedes modificar la información de esta cuenta.");
                                jTextField4.setText("");
                                jLabel12.setText("");
                                jPasswordField1.setText("");
                                jTextField3.setText("");
                                jPasswordField1.setEditable(false);
                                jTextField3.setEditable(false);
                            }
                        } else {
                            UIManager.put("control", new Color(51, 51, 51));
                            UIManager.put("OptionPane.messageFont", f);
                            UIManager.put("OptionPane.messageForeground", Color.white);
                            UIManager.put("OptionPane.messageIconImage", null);
                            JOptionPane.showMessageDialog(null, "Selecciona una registro antes de modificar los datos.");
                        }
                    } catch (SQLException ex) {

                    }
                } else {
                    if ("Borrar".equals(jLabel8.getText())) {

                        if (jTable1.getSelectedRow() != -1) {
                            String nom = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                            if (!user2.equals(nom)) {
                                if (!"Key".equals(nom)) {
                                    try {
                                        String sql = "DELETE FROM cuentas WHERE usuario='" + nom + "'";
                                        ps = (PreparedStatement) con.getConect().prepareStatement(sql);
                                        ps.executeUpdate();
                                        tabla();
                                        UIManager.put("control", new Color(51, 51, 51));
                                        UIManager.put("OptionPane.messageFont", f);
                                        UIManager.put("OptionPane.messageForeground", Color.white);
                                        UIManager.put("OptionPane.messageIconImage", null);
                                        JOptionPane.showMessageDialog(null, "Se ha borrado la cuenta.");
                                    } catch (SQLException e) {

                                    }
                                } else {
                                    UIManager.put("control", new Color(51, 51, 51));
                                    UIManager.put("OptionPane.messageFont", f);
                                    UIManager.put("OptionPane.messageForeground", Color.white);
                                    UIManager.put("OptionPane.messageIconImage", null);
                                    JOptionPane.showMessageDialog(null, "No se puede eliminar esta cuenta.");
                                }
                            } else {
                                UIManager.put("control", new Color(51, 51, 51));
                                UIManager.put("OptionPane.messageFont", f);
                                UIManager.put("OptionPane.messageForeground", Color.white);
                                UIManager.put("OptionPane.messageIconImage", null);
                                JOptionPane.showMessageDialog(null, "No se puede borrar la cuenta, ya que esta en uso.");
                            }
                        } else {
                            UIManager.put("control", new Color(51, 51, 51));
                            UIManager.put("OptionPane.messageFont", f);
                            UIManager.put("OptionPane.messageForeground", Color.white);
                            UIManager.put("OptionPane.messageIconImage", null);
                            JOptionPane.showMessageDialog(null, "Selecciona una registro antes de borrar los datos.");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MousePressed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2MousePressed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped

    }//GEN-LAST:event_jTextField4KeyTyped

    private void jComboBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1KeyReleased

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jComboBox1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBox1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1InputMethodTextChanged

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
        model.setRowCount(0);
        if (jComboBox1.getSelectedItem() == "Usuario") {
            try {
                ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM cuentas");
                ResultSet sr = ps.executeQuery();
                while (sr.next()) {
                    String com = "";
                    String s = sr.getString("usuario");
                    String c = sr.getString("contraseña");
                    String u = sr.getString("email");
                    String t = sr.getString("nivel");
                    String v = sr.getString("VIP");
                    try {
                        for (int i = 0; i < jTextField4.getText().length(); i++) {
                            com += s.charAt(i);
                            System.out.println(com);
                        }
                        if (jTextField4.getText().equals(com)) {
                            model.addRow(new Object[]{s, c, u, t, v});
                        }
                    } catch (Exception e) {

                    }

                }
            } catch (SQLException ex) {

            }
            jTable1.setModel(model);
        } else {
            if (jComboBox1.getSelectedItem() == "Email") {
                try {
                    ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM cuentas");
                    ResultSet sr = ps.executeQuery();
                    while (sr.next()) {
                        String com = "";
                        String s = sr.getString("usuario");
                        String c = sr.getString("contraseña");
                        String u = sr.getString("email");
                        String t = sr.getString("nivel");
                        String v = sr.getString("VIP");
                        try {
                            for (int i = 0; i < jTextField4.getText().length(); i++) {
                                com += u.charAt(i);
                                System.out.println(com);
                            }
                            if (jTextField4.getText().equals(com)) {
                                model.addRow(new Object[]{s, c, u, t, v});
                            }
                        } catch (Exception e) {

                        }

                    }
                } catch (SQLException ex) {

                }
                jTable1.setModel(model);
            } else {
                if (jComboBox1.getSelectedItem() == "Nivel") {
                    try {
                        ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM cuentas");
                        ResultSet sr = ps.executeQuery();
                        while (sr.next()) {
                            String com = "";
                            String s = sr.getString("usuario");
                            String c = sr.getString("contraseña");
                            String u = sr.getString("email");
                            String t = sr.getString("nivel");
                            String v = sr.getString("VIP");
                            try {
                                for (int i = 0; i < jTextField4.getText().length(); i++) {
                                    com += t.charAt(i);
                                    System.out.println(com);
                                }
                                if (jTextField4.getText().equals(com)) {
                                    model.addRow(new Object[]{s, c, u, t, v});
                                }
                            } catch (Exception e) {

                            }

                        }
                    } catch (SQLException ex) {

                    }
                    jTable1.setModel(model);
                } else {
                    if (jComboBox1.getSelectedItem() == "VIP") {
                        try {
                            ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM cuentas");
                            ResultSet sr = ps.executeQuery();
                            while (sr.next()) {
                                String com = "";
                                String s = sr.getString("usuario");
                                String c = sr.getString("contraseña");
                                String u = sr.getString("email");
                                String t = sr.getString("nivel");
                                String v = sr.getString("VIP");
                                try {
                                    for (int i = 0; i < jTextField4.getText().length(); i++) {
                                        com += v.charAt(i);
                                        System.out.println(com);
                                    }
                                    if (jTextField4.getText().equals(com)) {
                                        model.addRow(new Object[]{s, c, u, t, v});
                                    }
                                } catch (Exception e) {

                                }

                            }
                        } catch (SQLException ex) {

                        }
                        jTable1.setModel(model);
                    }
                }
            }

        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jPasswordField1.setEditable(true);
        jTextField3.setEditable(true);
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        int row = jTable1.getSelectedRow();
        jLabel12.setText(jTable1.getValueAt(row, 0).toString());
        jPasswordField1.setText(jTable1.getValueAt(row, 1).toString());
        jTextField3.setText(jTable1.getValueAt(row, 2).toString());
        if ("A".equals(jTable1.getValueAt(row, 3).toString())) {
            jRadioButton2.setSelected(true);

        } else {
            if ("V".equals(jTable1.getValueAt(row, 3).toString())) {
                jRadioButton1.setSelected(true);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        AdminMain ad;
        try {
            ad = new AdminMain(ss, tt);
            ad.show();
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    public void tabla() {
        model.setRowCount(0);
        try {
            ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM cuentas");
            ResultSet sr = ps.executeQuery();
            while (sr.next()) {
                String s = sr.getString("usuario");
                String c = sr.getString("contraseña");
                String u = sr.getString("email");
                String t = sr.getString("nivel");
                String v = sr.getString("VIP");
                model.addRow(new Object[]{s, c, u, t, v});

            }
        } catch (SQLException ex) {

        }
        jTable1.setModel(model);
        jTable1.updateUI();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOperaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOperaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOperaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOperaciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOperaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
