package cinesa;

import com.mysql.jdbc.PreparedStatement;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Paint;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saulg
 */
public class AdminOperacionesFunciones extends javax.swing.JFrame {

    /**
     * Creates new form Cine
     */
    Controlador con = new Controlador();
    PreparedStatement ps;
    Hora hr = new Hora();
    Font f = new Font("Franklin Gothic Demi Cond", Font.PLAIN, 18);
    boolean x = true;
    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel model2 = new DefaultTableModel();
    String ss;
    String tt;

    public AdminOperacionesFunciones(String user, String password) throws SQLException {
        setUndecorated(true);
        setSize(1200, 690);
        Shape forma = new RoundRectangle2D.Double(0, -0, getBounds().width, getBounds().height, 30, 30);
        setShape(forma);
        //this.pack();
        setLocationRelativeTo(null);
        setVisible(true);
        initComponents();
        jLabel1.setText("A");
        hr.setTexto(jLabel7);
        hr.start();
        jLabel1.setText("Administrador: " + user);
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesNoSelect.png")));
        jButton6.setBackground(new Color(105, 252, 205));
        jButton6.setContentAreaFilled(false);
        jLabel9.setVisible(false);
        jLabel2.setVisible(false);
        jLabel15.setVisible(false);

        jLabel8.setVisible(false);
        jButton6.setVisible(false);
        jTable1.setVisible(false);
        jScrollPane1.setVisible(false);
        model.addColumn("ID Película");
        model.addColumn("Nombre");

        model2.addColumn("ID Función");
        model2.addColumn("ID Película");
        model2.addColumn("Nombre");
        model2.addColumn("Sala");
        model2.addColumn("Hora");
        model2.addColumn("Fecha");
        jLabel11.setVisible(false);
        jLabel17.setVisible(false);
        jLabel12.setVisible(false);
        jLabel10.setVisible(false);
        jLabel25.setVisible(false);

        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField8.setVisible(false);
        jLabel18.setVisible(false);
        jLabel25.setVisible(false);
        jLabel25.setVisible(false);
        jButton6.setVisible(false);
        System.out.println(jScrollPane1.getX() + " " + jScrollPane1.getY() + " " + jScrollPane1.getWidth() + " " + jScrollPane1.getHeight());
        jComboBox1.setVisible(false);

        ss = user;
        tt = password;
        jComboBox2.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jTextField1.setVisible(false);
        jScrollPane2.setVisible(false);
        jTable2.setVisible(false);
    }

    private AdminOperacionesFunciones() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1037, 495));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 690));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 690));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(null);

        jTextField8.setBackground(new java.awt.Color(242, 242, 242));
        jTextField8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(51, 51, 51));
        jTextField8.setBorder(null);
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(730, 390, 250, 40);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 0, 310, 40);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(660, 0, 240, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FondoSup.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, -530, 680, 580);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sala");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(600, 340, 110, 30);

        jButton1.setToolTipText("Buscar cuenta");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton1MouseWheelMoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(155, 175, 80, 80);

        jButton3.setToolTipText("Modificar cuenta");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton3MouseWheelMoved(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(253, 175, 80, 80);

        jButton4.setToolTipText("Borrar cuenta");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton4MouseWheelMoved(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(345, 175, 80, 80);

        jButton5.setToolTipText("Agregar cuenta");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton5MouseMoved(evt);
            }
        });
        jButton5.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton5MouseWheelMoved(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(60, 170, 85, 85);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Funciones");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 110, 1010, 40);

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Registrar");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(720, 590, 160, 40);

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Hora");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(930, 200, 60, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1160, 430, 680, 600);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(-600, 270, 680, 600);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Boton2.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton6MouseMoved(evt);
            }
        });
        jButton6.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton6MouseWheelMoved(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(720, 570, 160, 90);

        jTable1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 22)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Contraseña", "Email", "Nivel", "VIP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(153, 153, 255));
        jTable1.setOpaque(false);
        jTable1.setRowHeight(28);
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(560, 450, 500, 100);

        jLabel25.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Buscar:");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(600, 390, 110, 30);

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ID Película");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(970, 340, 100, 30);

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Fecha de la función");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(610, 200, 160, 30);

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ID Función");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(860, 340, 80, 30);

        jTextField3.setBackground(new java.awt.Color(242, 242, 242));
        jTextField3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(570, 235, 250, 40);

        jTextField5.setBackground(new java.awt.Color(242, 242, 242));
        jTextField5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 51, 51));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setBorder(null);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(570, 297, 180, 37);

        jTextField6.setBackground(new java.awt.Color(242, 242, 242));
        jTextField6.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(51, 51, 51));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setBorder(null);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(870, 237, 180, 38);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BarraGrisS.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(710, 380, 290, 60);

        jLabel18.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(833, 220, 40, 30);

        jComboBox1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Película", "Sala", "Fecha", "Hora" }));
        jComboBox1.setLightWeightPopupEnabled(false);
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(872, 207, 190, 40);

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(980, 300, 70, 30);

        jLabel19.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel19);
        jLabel19.setBounds(867, 300, 70, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MenuFunciones.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(550, 170, 520, 230);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OperacionesNoSelect.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel4MouseMoved(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 60, 1080, 230);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegresarB.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(58, 10, 90, 70);

        jTable2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 22)); // NOI18N
        jTable2.setForeground(new java.awt.Color(51, 51, 51));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(153, 153, 255));
        jTable2.setRowHeight(28);
        jTable2.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTable2MouseDragged(evt);
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(110, 352, 390, 250);

        jLabel21.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Buscar:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(130, 295, 70, 21);

        jComboBox2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Película", "Sala", "Fecha", "Hora" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(220, 620, 160, 40);

        jTextField1.setBackground(new java.awt.Color(242, 242, 242));
        jTextField1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setBorder(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(220, 286, 250, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BarraGrisS.png"))); // NOI18N
        jPanel1.add(jLabel20);
        jLabel20.setBounds(200, 280, 290, 50);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CerrarP.png"))); // NOI18N
        jButton7.setToolTipText("Cerrar Aplicación");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(1110, 10, 70, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesNoSelect.png")));
        jButton6.setContentAreaFilled(false);
        jButton6.setIcon(new ImageIcon(getClass().getResource("/Images/Boton2.png")));
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesNoSelect.png")));
    }//GEN-LAST:event_jLabel4MouseMoved

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesSearch.png")));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseWheelMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel5.setText("Búsqueda de funciones");
        jLabel11.setVisible(false);
        jLabel10.setVisible(false);
        jLabel9.setVisible(false);
        jLabel2.setVisible(false);
        jLabel12.setVisible(false);
        jLabel17.setVisible(false);
        jTextField3.setVisible(false);
        jTextField6.setVisible(false);
        jLabel19.setVisible(false);
        jTextField5.setVisible(false);
        jLabel15.setVisible(false);
        jButton6.setVisible(false);
        jLabel8.setVisible(false);
        jTable1.setVisible(true);
        jScrollPane1.setVisible(true);
        jScrollPane1.setSize(1000, 290);
        jScrollPane1.setLocation(110, 305);
        jLabel25.setLocation(460, 210);
        jLabel25.setVisible(true);
        jTextField8.setVisible(true);
        jTextField8.setLocation(590, 209);
        jLabel13.setLocation(570, 200);
        jLabel13.setVisible(true);
        model = new DefaultTableModel();
        model.addColumn("ID Función");

        model.addColumn("ID Película");
        model.addColumn("Nombre película");
        model.addColumn("Sala");
        model.addColumn("Hora");
        model.addColumn("Fecha");
        jComboBox1.setVisible(true);
        jComboBox2.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jTextField1.setVisible(false);
        jScrollPane2.setVisible(false);
        jTable2.setVisible(false);
        jLabel19.setVisible(false);
        jLabel19.setText("");
        jTextField8.setText("");
        jLabel19.setVisible(false);
        jLabel19.setText("");
        tabla2();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesModify.png")));
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton3MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseWheelMoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel8.setText("Modificar");
        jLabel5.setText("Modificar funciones");
        jLabel5.setVisible(true);
        jLabel11.setVisible(true);
        jTextField3.setVisible(true);
        jTextField3.setEditable(false);
        jTextField3.setLocation(570, 235);
        jTextField5.setVisible(true);
        jTextField5.setEditable(false);
        jTextField6.setVisible(true);
        jTextField6.setEditable(false);
        jLabel19.setVisible(true);
        jLabel15.setVisible(true);
        jScrollPane1.setLocation(560, 450);
        jScrollPane1.setSize(500, 100);
        jLabel10.setVisible(true);
        jLabel2.setVisible(true);
        jLabel12.setVisible(true);
        jLabel17.setVisible(true);
        jLabel9.setVisible(true);
        jLabel25.setLocation(600, 390);
        jLabel13.setLocation(710, 380);
        jTextField8.setLocation(730, 390);
        jLabel25.setVisible(false);
        jLabel13.setVisible(false);
        jTextField8.setVisible(false);
        jComboBox1.setVisible(false);
        jLabel8.setText("Modificar");
        jButton6.setLocation(720, 390);
        jLabel8.setLocation(720, 410);
        jScrollPane1.setVisible(false);
        jTable1.setVisible(false);
        jComboBox2.setVisible(true);
        jLabel20.setVisible(true);
        jLabel21.setVisible(true);
        jTextField1.setVisible(true);
        jScrollPane2.setVisible(true);
        jTable2.setVisible(true);
        jLabel19.setVisible(false);
        jLabel19.setText("");
        jLabel15.setText("");
        jLabel15.setEnabled(false);
        jTextField8.setText("");
        jLabel19.setVisible(true);
        jLabel19.setText("");
        model = new DefaultTableModel();
        model.addColumn("ID Película");
        model.addColumn("Nombre");
        jButton6.setVisible(false);
        jLabel8.setVisible(false);
        tabla();
        tabla3();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesDelete.png")));
    }//GEN-LAST:event_jButton4MouseMoved

    private void jButton4MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton4MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseWheelMoved

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        jLabel5.setText("Borrar funciones");
        jTable1.setVisible(true);
        //jTable1.setSize(800, 400);
        //jTable1.setLocation(100, 150);
        jScrollPane1.setVisible(true);
        jScrollPane1.setSize(1000, 230);
        jScrollPane1.setLocation(110, 305);

        jLabel9.setVisible(true);
        jLabel8.setVisible(true);
        jLabel8.setText("Borrar");
        jButton6.setVisible(true);
        jButton6.setLocation(530, 570);
        jLabel8.setLocation(530, 595);
        jScrollPane2.setVisible(false);
        jTable2.setVisible(false);
        jLabel11.setVisible(false);
        jComboBox1.setVisible(true);
        jComboBox2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField6.setVisible(false);
        jTextField5.setVisible(false);
        jLabel19.setVisible(false);
        jLabel15.setVisible(false);
        jLabel10.setVisible(false);
        jLabel9.setVisible(false);
        jLabel2.setVisible(false);
        jLabel12.setVisible(false);
        jLabel17.setVisible(false);
        jLabel21.setVisible(false);
        jLabel25.setLocation(460, 210);
        jLabel25.setVisible(true);
        jLabel19.setText("");
        jTextField8.setText("");
        jLabel15.setText("");
        jLabel19.setText("");
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        // TODO add your handling code here:
        jLabel18.setText("");
        jLabel13.setLocation(570, 200);
        jLabel13.setVisible(true);
        jTextField8.setVisible(true);
        jTextField8.setLocation(590, 209);
        model = new DefaultTableModel();
        model.addColumn("ID Función");
        model.addColumn("ID Película");
        model.addColumn("Nombre película");
        model.addColumn("Sala");
        model.addColumn("Hora");
        model.addColumn("Fecha");
        jTextField1.setVisible(false);
        jLabel20.setVisible(false);
        tabla2();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesAdd.png")));
    }//GEN-LAST:event_jButton5MouseMoved

    private void jButton5MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton5MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseWheelMoved

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextField3.setText("");

        jTextField3.setLocation(570, 235);
        jTextField5.setVisible(true);
        jTextField6.setVisible(true);
        jTextField3.setVisible(true);
        jLabel2.setVisible(true);
        jLabel10.setVisible(true);
        jLabel12.setVisible(true);
        jLabel9.setVisible(true);
        jLabel15.setVisible(true);
        jLabel17.setVisible(true);
        jLabel8.setVisible(true);
        jButton6.setVisible(true);
        jLabel5.setText("Registro de funciones");
        jScrollPane1.setVisible(false);
        jLabel11.setVisible(true);
        jLabel13.setVisible(false);
        jTextField8.setVisible(false);
        jLabel18.setVisible(false);

        jTextField3.setEditable(true);
        jTextField5.setEditable(true);
        jTextField6.setEditable(true);
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        // TODO add your handling code here:
        jLabel18.setText("");
        jLabel8.setText("Registrar");
        jButton6.setLocation(720, 390);
        jLabel8.setLocation(720, 410);
        jLabel25.setLocation(600, 390);
        jLabel13.setLocation(710, 380);
        jTextField8.setLocation(730, 390);
        jScrollPane1.setLocation(560, 450);
        jScrollPane1.setSize(500, 100);
        jLabel25.setVisible(false);
        model = new DefaultTableModel();
        model.addColumn("ID Película");
        model.addColumn("Nombre");
        jComboBox1.setVisible(false);
        jComboBox2.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jTextField1.setVisible(false);
        jScrollPane2.setVisible(false);
        jTable2.setVisible(false);
        jLabel19.setVisible(false);
        jLabel19.setText("");
        jTextField8.setText("");
        jLabel15.setEnabled(true);
        jLabel15.setText("");

        jLabel19.setVisible(false);
        jLabel19.setText("");

        tabla();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton6MouseWheelMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton6MouseWheelMoved

    private void jButton6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseMoved
        // TODO add your handling code here:
        jButton6.setIcon(new ImageIcon(getClass().getResource("/Images/Boton1.png")));
    }//GEN-LAST:event_jButton6MouseMoved

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (("".equals(jTextField3.getText()) || "".equals(jTextField6.getText()) || "".equals(jTextField5.getText()) || "".equals(jLabel15.getText())) && !"Borrar".equals(jLabel8.getText())) {
            UIManager.put("control", new Color(51, 51, 51));
            UIManager.put("OptionPane.messageFont", f);
            UIManager.put("OptionPane.messageForeground", Color.white);
            UIManager.put("OptionPane.messageIconImage", null);
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar.\nIntente nuevamente.");
        } else {
            if ("Registrar".equals(jLabel8.getText())) {
                try {
                    String co = "SELECT * FROM funcion where hora = '" + jTextField6.getText() + "' AND fecha = '" + jTextField3.getText() + "' AND sala = '" + jTextField5.getText() + "'";
                    ResultSet sr = ps.executeQuery(co);
                    boolean p = false;
                    while (sr.next()) {
                        p = true;
                    }
                    if (p == false) {
                        String q = "insert into funcion(sala, hora, fecha, IDPelicula) values ('" + jTextField5.getText() + "', '" + jTextField6.getText() + "', '" + jTextField3.getText() + "', '" + jLabel15.getText() + "')";
                        ps = (PreparedStatement) con.getConect().prepareStatement(q);
                        ps.execute();
                        ps.close();
                        UIManager.put("control", new Color(51, 51, 51));
                        UIManager.put("OptionPane.messageFont", f);
                        UIManager.put("OptionPane.messageForeground", Color.white);
                        UIManager.put("OptionPane.messageIconImage", null);
                        JOptionPane.showMessageDialog(null, "La función se ha registrado correctamente.");
                        jTextField5.setText("");
                        jTextField6.setText("");
                        jTextField3.setText("");
                        jLabel15.setText("");
                        jTextField8.setVisible(false);
                        jTextField8.setText("");
                        jLabel13.setVisible(false);
                        jLabel25.setVisible(false);
                        jTable1.setVisible(false);
                        jScrollPane1.setVisible(false);
                        jButton6.setLocation(720, 390);
                        jLabel8.setLocation(720, 410);
                    } else {
                        UIManager.put("control", new Color(51, 51, 51));
                        UIManager.put("OptionPane.messageFont", f);
                        UIManager.put("OptionPane.messageForeground", Color.white);
                        UIManager.put("OptionPane.messageIconImage", null);
                        JOptionPane.showMessageDialog(null, "No se puede registrar la función porque la fecha, sala y/o sala coinciden");
                    }
                } catch (SQLException ex) {

                }
            } else {
                if ("Modificar".equals(jLabel8.getText())) {
                    try {
                        String q = "UPDATE funcion SET fecha='" + jTextField3.getText() + "', hora='" + jTextField6.getText() + "', sala='" + jTextField5.getText() + "', IDPelicula='" + jLabel15.getText() + "' WHERE IDFuncion='" + jLabel19.getText() + "'";
                        ps = (PreparedStatement) con.getConect().prepareStatement(q);
                        ps.executeUpdate();
                        tabla3();
                        UIManager.put("control", new Color(51, 51, 51));
                        UIManager.put("OptionPane.messageFont", f);
                        UIManager.put("OptionPane.messageForeground", Color.white);
                        UIManager.put("OptionPane.messageIconImage", null);
                        JOptionPane.showMessageDialog(null, "Se ha modificado la información de la pelicula.");
                    } catch (SQLException ex) {

                    }
                } else {
                    if ("Borrar".equals(jLabel8.getText())) {
                        if (jTable1.getSelectedRow() != -1) {
                            String ID = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                            try {
                                String sql2 = "DELETE FROM boletos WHERE IDFuncion='" + ID + "'";
                                ps = (PreparedStatement) con.getConect().prepareStatement(sql2);
                                ps.executeUpdate();
                                String sql = "DELETE FROM funcion WHERE IDFuncion='" + ID + "'";
                                ps = (PreparedStatement) con.getConect().prepareStatement(sql);
                                ps.executeUpdate();

                                tabla2();
                                UIManager.put("control", new Color(51, 51, 51));
                                UIManager.put("OptionPane.messageFont", f);
                                UIManager.put("OptionPane.messageForeground", Color.white);
                                UIManager.put("OptionPane.messageIconImage", null);
                                JOptionPane.showMessageDialog(null, "Se ha borrado la función.");
                            } catch (SQLException e) {

                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if ("Registro de funciones".equals(jLabel5.getText()) || "Modificar funciones".equals(jLabel5.getText())) {
            int row = jTable1.getSelectedRow();
            jLabel15.setText(jTable1.getValueAt(row, 0).toString());
            jTable1.setVisible(false);
            jScrollPane1.setVisible(false);
            jLabel25.setVisible(false);
            jTextField8.setVisible(false);
            jTextField8.setText("");
            jLabel13.setVisible(false);
            jButton6.setLocation(720, 390);
            jLabel8.setLocation(720, 410);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        // TODO add your handling code here:

        model.setRowCount(0);
        if ("Registro de funciones".equals(jLabel5.getText()) || "Modificar funciones".equals(jLabel5.getText())) {
            try {
                ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
                ResultSet sr = ps.executeQuery();
                while (sr.next()) {
                    String com = "";
                    String s = sr.getString("IDPelicula");
                    String c = sr.getString("nombre");
                    try {
                        for (int i = 0; i < jTextField8.getText().length(); i++) {
                            com += c.charAt(i);
                            System.out.println(com);
                        }
                        if (jTextField8.getText().equals(com)) {
                            model.addRow(new Object[]{s, c});
                        }
                    } catch (Exception e) {

                    }

                }
            } catch (SQLException ex) {

            }
            jTable1.setModel(model);
        } else {
            if ("Búsqueda de funciones".equals(jLabel5.getText()) || "Borrar funciones".equals(jLabel5.getText())) {
                if (jComboBox1.getSelectedItem() == "Película") {
                    try {
                        ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM funcion INNER JOIN pelicula ON funcion.IDPelicula = pelicula.IDPelicula");
                        ResultSet sr = ps.executeQuery();
                        while (sr.next()) {
                            String com = "";
                            String s = sr.getString("IDFuncion");
                            String c = sr.getString("IDPelicula");
                            String h = sr.getString("nombre");
                            String u = sr.getString("sala");
                            String t = sr.getString("hora");
                            String v = sr.getString("fecha");
                            try {
                                for (int i = 0; i < jTextField8.getText().length(); i++) {
                                    com += h.charAt(i);
                                    System.out.println(com);
                                }
                                if (jTextField8.getText().equals(com)) {
                                    model.addRow(new Object[]{s, c, h, u, t, v});
                                }
                            } catch (Exception e) {

                            }

                        }
                    } catch (SQLException ex) {

                    }
                    jTable1.setModel(model);
                } else {
                    if (jComboBox1.getSelectedItem() == "Sala") {
                        try {
                            ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM funcion INNER JOIN pelicula ON funcion.IDPelicula = pelicula.IDPelicula");
                            ResultSet sr = ps.executeQuery();
                            while (sr.next()) {
                                String com = "";
                                String s = sr.getString("IDFuncion");
                                String c = sr.getString("IDPelicula");
                                String h = sr.getString("nombre");
                                String u = sr.getString("sala");
                                String t = sr.getString("hora");
                                String v = sr.getString("fecha");
                                try {
                                    for (int i = 0; i < jTextField8.getText().length(); i++) {
                                        com += u.charAt(i);
                                        System.out.println(com);
                                    }
                                    if (jTextField8.getText().equals(com)) {
                                        model.addRow(new Object[]{s, c, h, u, t, v});
                                    }
                                } catch (Exception e) {

                                }

                            }
                        } catch (SQLException ex) {

                        }
                        jTable1.setModel(model);
                    } else {
                        if (jComboBox1.getSelectedItem() == "Hora") {
                            try {
                                ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM funcion INNER JOIN pelicula ON funcion.IDPelicula = pelicula.IDPelicula");
                                ResultSet sr = ps.executeQuery();
                                while (sr.next()) {
                                    String com = "";
                                    String s = sr.getString("IDFuncion");
                                    String c = sr.getString("IDPelicula");
                                    String h = sr.getString("nombre");
                                    String u = sr.getString("sala");
                                    String t = sr.getString("hora");
                                    String v = sr.getString("fecha");
                                    try {
                                        for (int i = 0; i < jTextField8.getText().length(); i++) {
                                            com += t.charAt(i);
                                            System.out.println(com);
                                        }
                                        if (jTextField8.getText().equals(com)) {
                                            model.addRow(new Object[]{s, c, h, u, t, v});
                                        }
                                    } catch (Exception e) {

                                    }

                                }
                            } catch (SQLException ex) {

                            }
                            jTable1.setModel(model);
                        } else {
                            if (jComboBox1.getSelectedItem() == "Fecha") {
                                try {
                                    ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM funcion INNER JOIN pelicula ON funcion.IDPelicula = pelicula.IDPelicula");
                                    ResultSet sr = ps.executeQuery();
                                    while (sr.next()) {
                                        String com = "";
                                        String s = sr.getString("IDFuncion");
                                        String c = sr.getString("IDPelicula");
                                        String h = sr.getString("nombre");
                                        String u = sr.getString("sala");
                                        String t = sr.getString("hora");
                                        String v = sr.getString("fecha");
                                        try {
                                            for (int i = 0; i < jTextField8.getText().length(); i++) {
                                                com += v.charAt(i);
                                                System.out.println(com);
                                            }
                                            if (jTextField8.getText().equals(com)) {
                                                model.addRow(new Object[]{s, c, h, u, t, v});
                                            }
                                        } catch (Exception e) {

                                        }

                                    }
                                } catch (SQLException ex) {

                                }
                                jTable1.setModel(model);
                            }
                        }
                    }
                }
            }
        }


    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        if ("Registro de funciones".equals(jLabel5.getText()) || ("Modificar funciones".equals(jLabel5.getText()) && jLabel15.isEnabled() == true)) {

            jLabel25.setVisible(true);
            jLabel25.setVisible(true);
            jButton6.setVisible(true);
            jTextField8.setVisible(true);
            jLabel13.setVisible(true);
            jTable1.setVisible(true);
            tabla();
            jScrollPane1.setVisible(true);
            jButton6.setLocation(720, 570);
            jLabel8.setLocation(720, 590);
        }

    }//GEN-LAST:event_jLabel15MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        AdminMain ad;
        try {
            ad = new AdminMain(ss, tt);
            ad.show();
            dispose();

        } catch (SQLException ex) {
            Logger.getLogger(AdminMain.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        jScrollPane1.setVisible(false);
        jTable1.setVisible(false);
        jLabel25.setVisible(false);
        jTextField8.setVisible(false);
        jLabel13.setVisible(false);
        jComboBox1.setVisible(false);
        jTextField3.setEditable(true);
        jTextField6.setEditable(true);
        jTextField5.setEditable(true);
        int row = jTable2.getSelectedRow();
        jLabel19.setText(jTable2.getValueAt(row, 0).toString());
        jLabel15.setText(jTable2.getValueAt(row, 1).toString());
        jTextField5.setText(jTable2.getValueAt(row, 3).toString());
        jTextField6.setText(jTable2.getValueAt(row, 4).toString());
        jTextField3.setText(jTable2.getValueAt(row, 5).toString());
        jLabel15.setEnabled(true);
        jTextField1.setText("");
        jButton6.setVisible(true);
        jLabel8.setVisible(true);

    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        model2.setRowCount(0);
        if (jComboBox2.getSelectedItem() == "Película") {
            try {
                ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM funcion INNER JOIN pelicula ON funcion.IDPelicula = pelicula.IDPelicula");
                ResultSet sr = ps.executeQuery();
                while (sr.next()) {
                    String com = "";
                    String s = sr.getString("IDFuncion");
                    String c = sr.getString("IDPelicula");
                    String h = sr.getString("nombre");
                    String u = sr.getString("sala");
                    String t = sr.getString("hora");
                    String v = sr.getString("fecha");
                    try {
                        for (int i = 0; i < jTextField1.getText().length(); i++) {
                            com += h.charAt(i);
                            System.out.println(com);
                        }
                        if (jTextField1.getText().equals(com)) {
                            model2.addRow(new Object[]{s, c, h, u, t, v});
                        }
                    } catch (Exception e) {

                    }

                }
            } catch (SQLException ex) {

            }
            jTable2.setModel(model2);
        } else {
            if (jComboBox2.getSelectedItem() == "Sala") {
                try {
                    ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM funcion INNER JOIN pelicula ON funcion.IDPelicula = pelicula.IDPelicula");
                    ResultSet sr = ps.executeQuery();
                    while (sr.next()) {
                        String com = "";
                        String s = sr.getString("IDFuncion");
                        String c = sr.getString("IDPelicula");
                        String h = sr.getString("nombre");
                        String u = sr.getString("sala");
                        String t = sr.getString("hora");
                        String v = sr.getString("fecha");
                        try {
                            for (int i = 0; i < jTextField1.getText().length(); i++) {
                                com += u.charAt(i);
                                System.out.println(com);
                            }
                            if (jTextField1.getText().equals(com)) {
                                model2.addRow(new Object[]{s, c, h, u, t, v});
                            }
                        } catch (Exception e) {

                        }

                    }
                } catch (SQLException ex) {

                }
                jTable2.setModel(model2);
            } else {
                if (jComboBox2.getSelectedItem() == "Hora") {
                    try {
                        ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM funcion INNER JOIN pelicula ON funcion.IDPelicula = pelicula.IDPelicula");
                        ResultSet sr = ps.executeQuery();
                        while (sr.next()) {
                            String com = "";
                            String s = sr.getString("IDFuncion");
                            String c = sr.getString("IDPelicula");
                            String h = sr.getString("nombre");
                            String u = sr.getString("sala");
                            String t = sr.getString("hora");
                            String v = sr.getString("fecha");
                            try {
                                for (int i = 0; i < jTextField1.getText().length(); i++) {
                                    com += t.charAt(i);
                                    System.out.println(com);
                                }
                                if (jTextField1.getText().equals(com)) {
                                    model2.addRow(new Object[]{s, c, h, u, t, v});
                                }
                            } catch (Exception e) {

                            }

                        }
                    } catch (SQLException ex) {

                    }
                    jTable2.setModel(model2);
                } else {
                    if (jComboBox2.getSelectedItem() == "Fecha") {
                        try {
                            ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM funcion INNER JOIN pelicula ON funcion.IDPelicula = pelicula.IDPelicula");
                            ResultSet sr = ps.executeQuery();
                            while (sr.next()) {
                                String com = "";
                                String s = sr.getString("IDFuncion");
                                String c = sr.getString("IDPelicula");
                                String h = sr.getString("nombre");
                                String u = sr.getString("sala");
                                String t = sr.getString("hora");
                                String v = sr.getString("fecha");
                                try {
                                    for (int i = 0; i < jTextField1.getText().length(); i++) {
                                        com += v.charAt(i);
                                        System.out.println(com);
                                    }
                                    if (jTextField1.getText().equals(com)) {
                                        model2.addRow(new Object[]{s, c, h, u, t, v});
                                    }
                                } catch (Exception e) {

                                }

                            }
                        } catch (SQLException ex) {

                        }
                        jTable2.setModel(model2);
                    }
                }
            }
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTable2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseDragged

    public void tabla() {
        model.setRowCount(0);
        try {
            ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
            ResultSet sr = ps.executeQuery();
            while (sr.next()) {
                String s = sr.getString("IDPelicula");
                String c = sr.getString("nombre");
                model.addRow(new Object[]{s, c});

            }
        } catch (SQLException ex) {

        }
        jTable1.setModel(model);
        jTable1.updateUI();
    }

    public void tabla2() {
        model.setRowCount(0);
        try {
            ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM funcion INNER JOIN pelicula ON funcion.IDPelicula = pelicula.IDPelicula");
            ResultSet sr = ps.executeQuery();
            while (sr.next()) {
                String s = sr.getString("IDFuncion");
                String c = sr.getString("IDPelicula");
                String h = sr.getString("nombre");
                String e = sr.getString("sala");
                String r = sr.getString("hora");
                String t = sr.getString("fecha");
                model.addRow(new Object[]{s, c, h, e, r, t});

            }
        } catch (SQLException ex) {

        }
        jTable1.setModel(model);
        jTable1.updateUI();
    }

    public void tabla3() {
        model2.setRowCount(0);
        try {
            ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM funcion INNER JOIN pelicula ON funcion.IDPelicula = pelicula.IDPelicula");
            ResultSet sr = ps.executeQuery();
            while (sr.next()) {
                String s = sr.getString("IDFuncion");
                String c = sr.getString("IDPelicula");
                String h = sr.getString("nombre");
                String e = sr.getString("sala");
                String r = sr.getString("hora");
                String t = sr.getString("fecha");
                model2.addRow(new Object[]{s, c, h, e, r, t});

            }
        } catch (SQLException ex) {

        }
        jTable2.setModel(model2);
        jTable2.updateUI();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOperacionesFunciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOperacionesFunciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOperacionesFunciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOperacionesFunciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOperacionesFunciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
