package cinesa;

import com.mysql.jdbc.PreparedStatement;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Paint;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saulg
 */
public class AdminOperacionesPeliculas extends javax.swing.JFrame {

    /**
     * Creates new form Cine
     */
    Controlador con = new Controlador();
    PreparedStatement ps;
    Hora hr = new Hora();
    Font f = new Font("Franklin Gothic Demi Cond", Font.PLAIN, 18);
    boolean x = true;
    DefaultTableModel model = new DefaultTableModel();
    String user2;
    String ruta;
    String ss;
    String tt;

    public AdminOperacionesPeliculas(String user, String password) throws SQLException {
        setUndecorated(true);
        setSize(1200, 690);
        Shape forma = new RoundRectangle2D.Double(0, -0, getBounds().width, getBounds().height, 30, 30);
        setShape(forma);
        //this.pack();
        setLocationRelativeTo(null);
        setVisible(true);
        initComponents();
        jLabel1.setText("A");
        jLabel5.setText("Películas");
        hr.setTexto(jLabel7);
        hr.start();
        user2 = user;
        jLabel1.setText("Administrador: " + user);
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesNoSelect.png")));
        jButton6.setBackground(new Color(105, 252, 205));
        jButton6.setContentAreaFilled(false);
        jLabel9.setVisible(false);
        jLabel2.setVisible(false);
        jLabel15.setVisible(false);

        jLabel8.setVisible(false);
        jButton6.setVisible(false);
        jTable1.setVisible(false);
        jScrollPane1.setVisible(false);
        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Descripción");
        model.addColumn("Duración");
        model.addColumn("Clasificación");
        model.addColumn("Fecha de Lanzamiento");
        model.addColumn("Género");
        jComboBox1.setVisible(false);

        jLabel11.setVisible(false);
        jLabel28.setVisible(false);
        jLabel17.setVisible(false);
        jLabel12.setVisible(false);
        jLabel10.setVisible(false);
        jLabel25.setVisible(false);
        jTextField1.setVisible(false);
        jTextField4.setVisible(false);
        jButton7.setVisible(false);
        jTextField7.setVisible(false);
        jTextField1.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField3.setVisible(false);
        jLabel13.setVisible(false);
        jTextField8.setVisible(false);
        jLabel18.setVisible(false);
        
        ss = user;
        tt = password;
    }

    private AdminOperacionesPeliculas() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1037, 495));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 690));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 690));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(null);

        jTextField8.setBackground(new java.awt.Color(242, 242, 242));
        jTextField8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(51, 51, 51));
        jTextField8.setBorder(null);
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(233, 290, 260, 40);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 0, 310, 40);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(660, 0, 240, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FondoSup.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, -530, 680, 580);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descripción");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 320, 110, 30);

        jButton1.setToolTipText("Buscar cuenta");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton1MouseWheelMoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(155, 175, 80, 80);

        jButton3.setToolTipText("Modificar cuenta");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton3MouseWheelMoved(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(253, 175, 80, 80);

        jButton4.setToolTipText("Borrar cuenta");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton4MouseWheelMoved(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(345, 175, 80, 80);

        jButton5.setToolTipText("Agregar cuenta");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton5MouseMoved(evt);
            }
        });
        jButton5.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton5MouseWheelMoved(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(60, 170, 85, 85);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Peliculas");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 110, 1010, 40);

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Registrar");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(720, 610, 160, 40);

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Imágen");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(950, 180, 60, 30);

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Clasificación");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(750, 550, 100, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1160, 430, 680, 600);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(-600, 270, 680, 600);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Boton2.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton6MouseMoved(evt);
            }
        });
        jButton6.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton6MouseWheelMoved(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(720, 590, 160, 90);

        jTable1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 22)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Contraseña", "Email", "Nivel", "VIP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(153, 153, 255));
        jTable1.setOpaque(false);
        jTable1.setRowHeight(28);
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(180, 620, 220, 50);

        jComboBox1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Descripción", "Duración", "Clasificación", "Fecha de Lanzamiento", "Género" }));
        jComboBox1.setBorder(null);
        jComboBox1.setLightWeightPopupEnabled(false);
        jComboBox1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jComboBox1InputMethodTextChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox1KeyReleased(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(950, 210, 140, 40);

        jLabel25.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Fecha de Lanzamiento");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(330, 430, 260, 30);

        jLabel28.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Duración");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(550, 550, 150, 30);

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Género");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(930, 550, 100, 30);

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nombre de la película");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(590, 180, 160, 30);

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ID");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(820, 180, 50, 30);

        jTextField1.setBackground(new java.awt.Color(242, 242, 242));
        jTextField1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(566, 506, 120, 40);

        jTextField3.setBackground(new java.awt.Color(242, 242, 242));
        jTextField3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(570, 213, 210, 44);

        jTextField4.setBackground(new java.awt.Color(242, 242, 242));
        jTextField4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 51, 51));
        jTextField4.setBorder(null);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(570, 301, 290, 80);

        jTextField5.setBackground(new java.awt.Color(242, 242, 242));
        jTextField5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 51, 51));
        jTextField5.setBorder(null);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(730, 506, 140, 40);

        jTextField6.setBackground(new java.awt.Color(242, 242, 242));
        jTextField6.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(51, 51, 51));
        jTextField6.setBorder(null);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(910, 506, 140, 40);

        jTextField7.setBackground(new java.awt.Color(242, 242, 242));
        jTextField7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(51, 51, 51));
        jTextField7.setBorder(null);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(567, 428, 300, 40);

        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(900, 240, 160, 200);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BarraGrisS.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(570, 200, 290, 60);

        jLabel18.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(833, 220, 40, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MenuPeliF.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(550, 130, 520, 500);

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OperacionesNoSelect.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel4MouseMoved(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 60, 1080, 230);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegresarB.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(58, 10, 90, 70);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CerrarP.png"))); // NOI18N
        jButton9.setToolTipText("Cerrar Aplicación");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(1110, 10, 70, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesNoSelect.png")));
        jButton6.setContentAreaFilled(false);
        jButton6.setIcon(new ImageIcon(getClass().getResource("/Images/Boton2.png")));
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesNoSelect.png")));
    }//GEN-LAST:event_jLabel4MouseMoved

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesSearch.png")));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseWheelMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField3.setText("");
        jLabel11.setVisible(false);
        jLabel28.setVisible(false);
        jLabel17.setVisible(false);
        jLabel12.setVisible(false);
        jLabel10.setVisible(false);
        jLabel25.setVisible(false);
        jTextField1.setVisible(false);
        jTextField4.setVisible(false);
        jButton7.setVisible(false);
        jTextField7.setVisible(false);
        jTextField1.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField8.setText("");
        jLabel9.setLocation(490, 210);
        jLabel9.setText("Buscar: ");
        jLabel2.setVisible(false);

        jLabel15.setVisible(false);
        jLabel5.setText("Búsqueda de películas");
        jTable1.setVisible(true);
        //jTable1.setSize(800, 400);
        //jTable1.setLocation(100, 150);
        jScrollPane1.setVisible(true);
        jScrollPane1.setSize(1000, 290);
        jScrollPane1.setLocation(110, 305);

        jLabel9.setVisible(true);
        jLabel8.setVisible(false);
        jButton6.setVisible(false);
        jComboBox1.setVisible(true);
        jLabel13.setVisible(true);
        jTextField3.setVisible(true);
        jTextField3.setLocation(585, 207);
        jLabel13.setLocation(570, 200);
        jTextField8.setVisible(false);
        jLabel18.setVisible(false);
        jComboBox1.setLocation(950, 210);
        tabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesModify.png")));
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton3MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseWheelMoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel8.setVisible(true);
        jLabel8.setText("Modificar");
        jButton6.setLocation(770, 580);
        jLabel8.setLocation(770, 605);
        jLabel8.setVisible(true);
        jButton6.setVisible(true);
        jLabel2.setVisible(false);

        jLabel15.setVisible(false);
        jLabel5.setText("Modificar películas");
        jTable1.setVisible(true);
        //jTable1.setSize(800, 400);
        //jTable1.setLocation(100, 150);
        jScrollPane1.setVisible(true);
        jScrollPane1.setSize(430, 270);
        jScrollPane1.setLocation(100, 345);
        jLabel9.setVisible(true);
        jLabel9.setVisible(true);
        jLabel8.setVisible(false);
        jButton6.setVisible(false);
        jComboBox1.setVisible(true);
        jLabel13.setVisible(true);
        jTextField3.setVisible(true);
        jTextField3.setLocation(580, 213);
        jLabel9.setLocation(490, 210);
        jLabel9.setText("Buscar: ");
        jLabel11.setVisible(true);
        jLabel11.setLocation(560, 130);
        jLabel13.setLocation(220, 280);
        jLabel9.setLocation(130, 290);
        jLabel9.setText("Buscar: ");
        jComboBox1.setLocation(240, 630);
        jTextField4.setVisible(true);
        jTextField4.setLocation(580, 301);
        jButton7.setLocation(910, 240);
        jButton7.setVisible(true);
        jTextField8.setVisible(true);
        jTextField7.setLocation(577, 428);
        jTextField7.setVisible(true);
        jTextField1.setLocation(576, 506);
        jTextField1.setVisible(true);
        jTextField5.setLocation(740, 506);
        jTextField5.setVisible(true);
        jTextField6.setVisible(true);
        jTextField6.setLocation(920, 506);
        jLabel18.setVisible(true);

        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField7.setEditable(false);
        jTextField1.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jButton7.setEnabled(false);

        jLabel10.setVisible(false);
        jLabel12.setVisible(false);
        jLabel25.setVisible(false);
        jLabel28.setVisible(false);
        jLabel17.setVisible(false);

        jLabel18.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField7.setText("");
        jTextField1.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jButton7.setIcon(null);
        jButton6.setLocation(730, 590);
        jButton6.setVisible(true);
        jLabel8.setLocation(730, 610);
        jLabel8.setVisible(true);
        jLabel8.setText("Modificar");
        jTextField8.setText("");
        tabla();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesDelete.png")));
    }//GEN-LAST:event_jButton4MouseMoved

    private void jButton4MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton4MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseWheelMoved

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        jLabel2.setVisible(false);

        jLabel15.setVisible(false);
        jLabel5.setText("Borrar películas");
        jTable1.setVisible(true);
        //jTable1.setSize(800, 400);
        //jTable1.setLocation(100, 150);
        jScrollPane1.setVisible(true);
        jScrollPane1.setSize(1000, 230);
        jScrollPane1.setLocation(110, 305);

        jLabel9.setVisible(true);
        jLabel8.setVisible(true);
        jLabel8.setText("Borrar");
        jButton6.setLocation(530, 570);
        jButton6.setVisible(true);
        jLabel8.setLocation(530, 595);
        jTextField3.setEditable(true);
        jTextField3.setVisible(true);
        jTextField3.setLocation(585, 207);

        jComboBox1.setLocation(950, 210);
        jComboBox1.setVisible(true);
        jLabel13.setVisible(true);
        jLabel13.setLocation(570, 200);
        jLabel11.setVisible(false);

        jTextField3.setText("");
        jLabel11.setVisible(false);
        jLabel28.setVisible(false);
        jLabel17.setVisible(false);
        jLabel12.setVisible(false);
        jLabel10.setVisible(false);
        jLabel25.setVisible(false);
        jTextField1.setVisible(false);
        jTextField4.setVisible(false);
        jButton7.setVisible(false);
        jTextField7.setVisible(false);
        jTextField1.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);

        jLabel9.setLocation(490, 210);
        jLabel9.setText("Buscar: ");
        jTextField8.setVisible(false);
        jTextField8.setText("");
        tabla();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseMoved
        // TODO add your handling code here:
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/Images/OperacionesAdd.png")));
    }//GEN-LAST:event_jButton5MouseMoved

    private void jButton5MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton5MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseWheelMoved

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextField3.setText("");

        jTextField1.setVisible(true);
        jTextField4.setVisible(true);
        jButton7.setVisible(true);
        jTextField7.setVisible(true);
        jTextField1.setVisible(true);
        jTextField5.setVisible(true);
        jTextField6.setVisible(true);
        jTextField3.setVisible(true);

        jLabel2.setVisible(true);
        jLabel10.setVisible(true);
        jLabel12.setVisible(true);
        jLabel9.setVisible(true);
        jLabel25.setVisible(true);
        jLabel25.setVisible(true);
        jLabel28.setVisible(true);
        jLabel15.setVisible(true);
        jLabel17.setVisible(true);

        jLabel8.setVisible(true);
        jButton6.setVisible(true);
        jLabel5.setText("Registro de películas");
        jScrollPane1.setVisible(false);
        jComboBox1.setVisible(false);
        jLabel11.setVisible(true);
        jLabel9.setLocation(950, 180);
        jLabel9.setText("Imagen");
        jLabel13.setVisible(false);
        jTextField3.setLocation(570, 213);
        jLabel11.setLocation(550, 130);
        jTextField8.setVisible(false);

        jTextField6.setLocation(910, 506);
        jTextField4.setLocation(570, 301);
        jButton7.setLocation(900, 240);
        jTextField7.setLocation(567, 428);
        jTextField1.setLocation(566, 506);
        jTextField5.setLocation(730, 506);
        jTextField3.setLocation(570, 213);
        jLabel18.setVisible(false);

        jTextField3.setEditable(true);
        jTextField4.setEditable(true);
        jTextField7.setEditable(true);
        jTextField1.setEditable(true);
        jTextField5.setEditable(true);
        jTextField6.setEditable(true);
        jButton7.setEnabled(true);
        jLabel8.setText("Registrar");

        jTextField3.setText("");
        jTextField4.setText("");
        jTextField7.setText("");
        jTextField1.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jButton7.setIcon(null);
        // TODO add your handling code here:
        jButton6.setLocation(720, 590);
        jLabel8.setLocation(720, 610);
        jLabel18.setText("");
        jButton6.setLocation(720, 590);
        jButton6.setVisible(true);
        jLabel8.setLocation(720, 610);
        jLabel8.setVisible(true);
        jLabel8.setText("Registrar");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton6MouseWheelMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton6MouseWheelMoved

    private void jButton6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseMoved
        // TODO add your handling code here:
        jButton6.setIcon(new ImageIcon(getClass().getResource("/Images/Boton1.png")));
    }//GEN-LAST:event_jButton6MouseMoved

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (("".equals(jTextField3.getText()) || "".equals(jTextField4.getText()) || "".equals(jTextField7.getText()) || "".equals(jTextField1.getText()) || "".equals(jTextField5.getText()) || "".equals(jTextField6.getText()) || jButton7.getIcon() == null) && !"Borrar".equals(jLabel8.getText())) {
            UIManager.put("control", new Color(51, 51, 51));
            UIManager.put("OptionPane.messageFont", f);
            UIManager.put("OptionPane.messageForeground", Color.white);
            UIManager.put("OptionPane.messageIconImage", null);
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar.\nIntente nuevamente.");
        } else {
            if ("Registrar".equals(jLabel8.getText())) {
                try {
                    String ruta2 = "";
                    for (int i = 0; i < ruta.length(); i++) {

                        if (ruta.charAt(i) == '\\') {
                            ruta2 += "´";
                        } else {
                            ruta2 += ruta.charAt(i);
                        }
                    }
                    System.out.println(ruta2);
                    String q = "insert into pelicula(nombre, descripcion, duracion, clasificacion, fechaLanzamiento, genero, ruta) values ('" + jTextField3.getText() + "', '" + jTextField4.getText() + "', '" + jTextField1.getText() + "', '" + jTextField5.getText() + "', '" + jTextField7.getText() + "', '" + jTextField6.getText() + "', '" + ruta2 + "')";
                    ps = (PreparedStatement) con.getConect().prepareStatement(q);
                    ps.execute();
                    ps.close();
                    UIManager.put("control", new Color(51, 51, 51));
                    UIManager.put("OptionPane.messageFont", f);
                    UIManager.put("OptionPane.messageForeground", Color.white);
                    UIManager.put("OptionPane.messageIconImage", null);
                    JOptionPane.showMessageDialog(null, "La película se ha registrado correctamente.");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField7.setText("");
                    jTextField1.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jButton7.setIcon(null);
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            } else {
                if ("Modificar".equals(jLabel8.getText())) {
                    try {
                        String sql = "UPDATE pelicula SET nombre='" + jTextField3.getText() + "', descripcion='" + jTextField4.getText() + "', duracion='" + jTextField1.getText() + "', clasificacion='" + jTextField5.getText() + "', fechaLanzamiento='" + jTextField7.getText() + "', genero='" + jTextField6.getText() + "', ruta='" + ruta + "' WHERE IDPelicula='" + jLabel18.getText() + "'";
                        ps = (PreparedStatement) con.getConect().prepareStatement(sql);
                        ps.executeUpdate();
                        tabla();
                        jTextField3.setEditable(false);
                        jTextField4.setEditable(false);
                        jTextField7.setEditable(false);
                        jTextField1.setEditable(false);
                        jTextField5.setEditable(false);
                        jTextField6.setEditable(false);
                        jButton7.setEnabled(false);

                        jLabel18.setText("");
                        jTextField3.setText("");
                        jTextField4.setText("");
                        jTextField7.setText("");
                        jTextField1.setText("");
                        jTextField5.setText("");
                        jTextField6.setText("");
                        jButton7.setIcon(null);
                        UIManager.put("control", new Color(51, 51, 51));
                        UIManager.put("OptionPane.messageFont", f);
                        UIManager.put("OptionPane.messageForeground", Color.white);
                        UIManager.put("OptionPane.messageIconImage", null);
                        JOptionPane.showMessageDialog(null, "Se ha modificado la información de la pelicula.");
                    } catch (SQLException ex) {

                    }
                } else {
                    if ("Borrar".equals(jLabel8.getText())) {
                        if (jTable1.getSelectedRow() != -1) {
                            String ID = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
                            try {
                                String sql = "DELETE FROM pelicula WHERE IDPelicula='" + ID + "'";
                                ps = (PreparedStatement) con.getConect().prepareStatement(sql);
                                ps.executeUpdate();
                                tabla();
                                UIManager.put("control", new Color(51, 51, 51));
                                UIManager.put("OptionPane.messageFont", f);
                                UIManager.put("OptionPane.messageForeground", Color.white);
                                UIManager.put("OptionPane.messageIconImage", null);
                                JOptionPane.showMessageDialog(null, "Se ha borrado la pelicula");
                            } catch (SQLException e) {

                            }
                        }
                    }
                }
            }

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1KeyReleased

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jComboBox1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBox1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1InputMethodTextChanged

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if ("Modificar películas".equals(jLabel5.getText())) {
            jTextField3.setEditable(true);
            jTextField4.setEditable(true);
            jTextField7.setEditable(true);
            jTextField1.setEditable(true);
            jTextField5.setEditable(true);
            jTextField6.setEditable(true);
            jButton7.setEnabled(true);

            int row = jTable1.getSelectedRow();
            jLabel18.setText(jTable1.getValueAt(row, 0).toString());
            jTextField3.setText(jTable1.getValueAt(row, 1).toString());
            jTextField4.setText(jTable1.getValueAt(row, 2).toString());
            jTextField1.setText(jTable1.getValueAt(row, 3).toString());
            jTextField5.setText(jTable1.getValueAt(row, 4).toString());
            jTextField7.setText(jTable1.getValueAt(row, 5).toString());
            jTextField6.setText(jTable1.getValueAt(row, 6).toString());
            try {
                ps = (PreparedStatement) con.getConect().prepareStatement("SELECT  * FROM pelicula WHERE IDPelicula='" + jLabel18.getText() + "'");
                ResultSet sr = ps.executeQuery();
                while (sr.next()) {
                    String s = sr.getString("ruta");
                    s = s.replace('´', '\\');
                    Image im = new ImageIcon(s).getImage();
                    ImageIcon ic = new ImageIcon(im.getScaledInstance(jButton7.getWidth(), jButton7.getHeight(), Image.SCALE_SMOOTH));
                    jButton7.setIcon(ic);
                    ruta = s.replace('\\', '´');
                }
            } catch (SQLException ex) {

            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        ruta = "";
        JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter fi = new FileNameExtensionFilter("JPG & PNG", "JPG", "PNG");
        jf.setFileFilter(fi);

        int respuesta = jf.showOpenDialog(this);
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            ruta = jf.getSelectedFile().getPath();
            Image im = new ImageIcon(ruta).getImage();
            ImageIcon ic = new ImageIcon(im.getScaledInstance(jButton7.getWidth(), jButton7.getHeight(), Image.SCALE_SMOOTH));
            jButton7.setIcon(ic);
            ruta = ruta.replace('\\', '´');
            System.out.println(ruta);
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        if ("Búsqueda de películas".equals(jLabel5.getText()) || "Borrar películas".equals(jLabel5.getText())) {
            model.setRowCount(0);
            if (jComboBox1.getSelectedItem() == "Nombre") {
                try {
                    ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
                    ResultSet sr = ps.executeQuery();
                    while (sr.next()) {
                        String com = "";
                        String s = sr.getString("IDPelicula");
                        String c = sr.getString("nombre");
                        String u = sr.getString("descripcion");
                        String t = sr.getString("duracion");
                        String v = sr.getString("clasificacion");
                        String xx = sr.getString("fechaLanzamiento");
                        String d = sr.getString("genero");
                        try {
                            for (int i = 0; i < jTextField3.getText().length(); i++) {
                                com += c.charAt(i);
                                System.out.println(com);
                            }
                            if (jTextField3.getText().equals(com)) {
                                model.addRow(new Object[]{s, c, u, t, v, xx, d});
                            }
                        } catch (Exception e) {

                        }

                    }
                } catch (SQLException ex) {

                }
                jTable1.setModel(model);
            } else {
                if (jComboBox1.getSelectedItem() == "Descripción") {
                    try {
                        ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
                        ResultSet sr = ps.executeQuery();
                        while (sr.next()) {
                            String com = "";
                            String s = sr.getString("IDPelicula");
                            String c = sr.getString("nombre");
                            String u = sr.getString("descripcion");
                            String t = sr.getString("duracion");
                            String v = sr.getString("clasificacion");
                            String x = sr.getString("fechaLanzamiento");
                            String d = sr.getString("genero");
                            try {
                                for (int i = 0; i < jTextField3.getText().length(); i++) {
                                    com += u.charAt(i);
                                    System.out.println(com);
                                }
                                if (jTextField3.getText().equals(com)) {
                                    model.addRow(new Object[]{s, c, u, t, v, x, d});
                                }
                            } catch (Exception e) {

                            }

                        }
                    } catch (SQLException ex) {

                    }
                    jTable1.setModel(model);
                } else {
                    if (jComboBox1.getSelectedItem() == "Duración") {
                        try {
                            ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
                            ResultSet sr = ps.executeQuery();
                            while (sr.next()) {
                                String com = "";
                                String s = sr.getString("IDPelicula");
                                String c = sr.getString("nombre");
                                String u = sr.getString("descripcion");
                                String t = sr.getString("duracion");
                                String v = sr.getString("clasificacion");
                                String x = sr.getString("fechaLanzamiento");
                                String d = sr.getString("genero");
                                try {
                                    for (int i = 0; i < jTextField3.getText().length(); i++) {
                                        com += t.charAt(i);
                                        System.out.println(com);
                                    }
                                    if (jTextField3.getText().equals(com)) {
                                        model.addRow(new Object[]{s, c, u, t, v, x, d});
                                    }
                                } catch (Exception e) {

                                }

                            }
                        } catch (SQLException ex) {

                        }
                        jTable1.setModel(model);
                    } else {
                        if (jComboBox1.getSelectedItem() == "Clasificación") {
                            try {
                                ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
                                ResultSet sr = ps.executeQuery();
                                while (sr.next()) {
                                    String com = "";
                                    String s = sr.getString("IDPelicula");
                                    String c = sr.getString("nombre");
                                    String u = sr.getString("descripcion");
                                    String t = sr.getString("duracion");
                                    String v = sr.getString("clasificacion");
                                    String x = sr.getString("fechaLanzamiento");
                                    String d = sr.getString("genero");
                                    try {
                                        for (int i = 0; i < jTextField3.getText().length(); i++) {
                                            com += v.charAt(i);
                                            System.out.println(com);
                                        }
                                        if (jTextField3.getText().equals(com)) {
                                            model.addRow(new Object[]{s, c, u, t, v, x, d});
                                        }
                                    } catch (Exception e) {

                                    }

                                }
                            } catch (SQLException ex) {

                            }
                            jTable1.setModel(model);
                        } else {
                            if (jComboBox1.getSelectedItem() == "Fecha de Lanzamiento") {
                                try {
                                    ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
                                    ResultSet sr = ps.executeQuery();
                                    while (sr.next()) {
                                        String com = "";
                                        String s = sr.getString("IDPelicula");
                                        String c = sr.getString("nombre");
                                        String u = sr.getString("descripcion");
                                        String t = sr.getString("duracion");
                                        String v = sr.getString("clasificacion");
                                        String x = sr.getString("fechaLanzamiento");
                                        String d = sr.getString("genero");
                                        try {
                                            for (int i = 0; i < jTextField3.getText().length(); i++) {
                                                com += x.charAt(i);
                                                System.out.println(com);
                                            }
                                            if (jTextField3.getText().equals(com)) {
                                                model.addRow(new Object[]{s, c, u, t, v, x, d});
                                            }
                                        } catch (Exception e) {

                                        }

                                    }
                                } catch (SQLException ex) {

                                }
                                jTable1.setModel(model);
                            } else {
                                if (jComboBox1.getSelectedItem() == "Género") {
                                    try {
                                        ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
                                        ResultSet sr = ps.executeQuery();
                                        while (sr.next()) {
                                            String com = "";
                                            String s = sr.getString("IDPelicula");
                                            String c = sr.getString("nombre");
                                            String u = sr.getString("descripcion");
                                            String t = sr.getString("duracion");
                                            String v = sr.getString("clasificacion");
                                            String x = sr.getString("fechaLanzamiento");
                                            String d = sr.getString("genero");
                                            try {
                                                for (int i = 0; i < jTextField3.getText().length(); i++) {
                                                    com += d.charAt(i);
                                                    System.out.println(com);
                                                }
                                                if (jTextField3.getText().equals(com)) {
                                                    model.addRow(new Object[]{s, c, u, t, v, x, d});
                                                }
                                            } catch (Exception e) {

                                            }

                                        }
                                    } catch (SQLException ex) {

                                    }
                                    jTable1.setModel(model);
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        // TODO add your handling code here:

        if ("Modificar películas".equals(jLabel5.getText())) {
            model.setRowCount(0);
            if (jComboBox1.getSelectedItem() == "Nombre") {
                try {
                    ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
                    ResultSet sr = ps.executeQuery();
                    while (sr.next()) {
                        String com = "";
                        String s = sr.getString("IDPelicula");
                        String c = sr.getString("nombre");
                        String u = sr.getString("descripcion");
                        String t = sr.getString("duracion");
                        String v = sr.getString("clasificacion");
                        String x = sr.getString("fechaLanzamiento");
                        String d = sr.getString("genero");
                        try {
                            for (int i = 0; i < jTextField8.getText().length(); i++) {
                                com += c.charAt(i);
                                System.out.println(com);
                            }
                            if (jTextField8.getText().equals(com)) {
                                model.addRow(new Object[]{s, c, u, t, v, x, d});
                            }
                        } catch (Exception e) {

                        }

                    }
                } catch (SQLException ex) {

                }
                jTable1.setModel(model);
            } else {
                if (jComboBox1.getSelectedItem() == "Descripción") {
                    try {
                        ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
                        ResultSet sr = ps.executeQuery();
                        while (sr.next()) {
                            String com = "";
                            String s = sr.getString("IDPelicula");
                            String c = sr.getString("nombre");
                            String u = sr.getString("descripcion");
                            String t = sr.getString("duracion");
                            String v = sr.getString("clasificacion");
                            String x = sr.getString("fechaLanzamiento");
                            String d = sr.getString("genero");
                            try {
                                for (int i = 0; i < jTextField8.getText().length(); i++) {
                                    com += u.charAt(i);
                                    System.out.println(com);
                                }
                                if (jTextField8.getText().equals(com)) {
                                    model.addRow(new Object[]{s, c, u, t, v, x, d});
                                }
                            } catch (Exception e) {

                            }

                        }
                    } catch (SQLException ex) {

                    }
                    jTable1.setModel(model);
                } else {
                    if (jComboBox1.getSelectedItem() == "Duración") {
                        try {
                            ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
                            ResultSet sr = ps.executeQuery();
                            while (sr.next()) {
                                String com = "";
                                String s = sr.getString("IDPelicula");
                                String c = sr.getString("nombre");
                                String u = sr.getString("descripcion");
                                String t = sr.getString("duracion");
                                String v = sr.getString("clasificacion");
                                String x = sr.getString("fechaLanzamiento");
                                String d = sr.getString("genero");
                                try {
                                    for (int i = 0; i < jTextField8.getText().length(); i++) {
                                        com += t.charAt(i);
                                        System.out.println(com);
                                    }
                                    if (jTextField8.getText().equals(com)) {
                                        model.addRow(new Object[]{s, c, u, t, v, x, d});
                                    }
                                } catch (Exception e) {

                                }

                            }
                        } catch (SQLException ex) {

                        }
                        jTable1.setModel(model);
                    } else {
                        if (jComboBox1.getSelectedItem() == "Clasificación") {
                            try {
                                ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
                                ResultSet sr = ps.executeQuery();
                                while (sr.next()) {
                                    String com = "";
                                    String s = sr.getString("IDPelicula");
                                    String c = sr.getString("nombre");
                                    String u = sr.getString("descripcion");
                                    String t = sr.getString("duracion");
                                    String v = sr.getString("clasificacion");
                                    String x = sr.getString("fechaLanzamiento");
                                    String d = sr.getString("genero");
                                    try {
                                        for (int i = 0; i < jTextField8.getText().length(); i++) {
                                            com += v.charAt(i);
                                            System.out.println(com);
                                        }
                                        if (jTextField8.getText().equals(com)) {
                                            model.addRow(new Object[]{s, c, u, t, v, x, d});
                                        }
                                    } catch (Exception e) {

                                    }

                                }
                            } catch (SQLException ex) {

                            }
                            jTable1.setModel(model);
                        } else {
                            if (jComboBox1.getSelectedItem() == "Fecha de Lanzamiento") {
                                try {
                                    ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
                                    ResultSet sr = ps.executeQuery();
                                    while (sr.next()) {
                                        String com = "";
                                        String s = sr.getString("IDPelicula");
                                        String c = sr.getString("nombre");
                                        String u = sr.getString("descripcion");
                                        String t = sr.getString("duracion");
                                        String v = sr.getString("clasificacion");
                                        String x = sr.getString("fechaLanzamiento");
                                        String d = sr.getString("genero");
                                        try {
                                            for (int i = 0; i < jTextField8.getText().length(); i++) {
                                                com += x.charAt(i);
                                                System.out.println(com);
                                            }
                                            if (jTextField8.getText().equals(com)) {
                                                model.addRow(new Object[]{s, c, u, t, v, x, d});
                                            }
                                        } catch (Exception e) {

                                        }

                                    }
                                } catch (SQLException ex) {

                                }
                                jTable1.setModel(model);
                            } else {
                                if (jComboBox1.getSelectedItem() == "Género") {
                                    try {
                                        ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
                                        ResultSet sr = ps.executeQuery();
                                        while (sr.next()) {
                                            String com = "";
                                            String s = sr.getString("IDPelicula");
                                            String c = sr.getString("nombre");
                                            String u = sr.getString("descripcion");
                                            String t = sr.getString("duracion");
                                            String v = sr.getString("clasificacion");
                                            String x = sr.getString("fechaLanzamiento");
                                            String d = sr.getString("genero");
                                            try {
                                                for (int i = 0; i < jTextField8.getText().length(); i++) {
                                                    com += d.charAt(i);
                                                    System.out.println(com);
                                                }
                                                if (jTextField8.getText().equals(com)) {
                                                    model.addRow(new Object[]{s, c, u, t, v, x, d});
                                                }
                                            } catch (Exception e) {

                                            }

                                        }
                                    } catch (SQLException ex) {

                                    }
                                    jTable1.setModel(model);
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        AdminMain ad;
        try {
            ad = new AdminMain(ss, tt);
            ad.show();
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    public void tabla() {
        model.setRowCount(0);
        try {
            ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula");
            ResultSet sr = ps.executeQuery();
            while (sr.next()) {
                String s = sr.getString("IDPelicula");
                String c = sr.getString("nombre");
                String u = sr.getString("descripcion");
                String t = sr.getString("duracion");
                String v = sr.getString("clasificacion");
                String x = sr.getString("fechaLanzamiento");
                String d = sr.getString("genero");
                model.addRow(new Object[]{s, c, u, t, v, x, d});

            }
        } catch (SQLException ex) {

        }
        jTable1.setModel(model);
        jTable1.updateUI();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOperacionesPeliculas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOperacionesPeliculas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOperacionesPeliculas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOperacionesPeliculas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOperacionesPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
