package cinesa;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.mysql.jdbc.PreparedStatement;
import java.awt.AWTException;
import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Paint;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.Robot;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.ButtonModel;
import javax.swing.ComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author saulg
 */
public class VentaBoletos5 extends javax.swing.JFrame {

    /**
     * Creates new form Cine
     */
    Controlador con = new Controlador();
    PreparedStatement ps;
    Hora hr = new Hora();
    Font f = new Font("Franklin Gothic Demi Cond", Font.PLAIN, 18);
    boolean xee = false;
    String s;
    String t;
    String u;
    String v;
    String w;

    public VentaBoletos5(String user, String password, String IDVenta, String IDFu, String IDPe) throws SQLException {
        setUndecorated(true);
        setSize(1200, 690);
        Shape forma = new RoundRectangle2D.Double(0, -0, getBounds().width, getBounds().height, 30, 30);
        setShape(forma);
        //this.pack();
        setLocationRelativeTo(null);
        setVisible(true);
        initComponents();
        jLabel1.setText("A");
        hr.setTexto(jLabel7);
        hr.start();
        jLabel1.setText("Vendedor: " + user);
        s = user;
        t = password;
        u = IDVenta;
        v = IDFu;
        w = IDPe;

    }

    private VentaBoletos5() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Menú de operaciones");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Disponible.png"))); // NOI18N

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Disponible.png"))); // NOI18N

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Disponible.png"))); // NOI18N

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Disponible.png"))); // NOI18N

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Disponible.png"))); // NOI18N

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Disponible.png"))); // NOI18N

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Disponible.png"))); // NOI18N

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Disponible.png"))); // NOI18N

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Disponible.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1037, 495));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 690));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 690));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CerrarP.png"))); // NOI18N
        jButton2.setToolTipText("Cerrar Aplicación");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1100, 10, 80, 70);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 0, 310, 40);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(660, 0, 240, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FondoSup.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, -530, 680, 580);

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Factura");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 100, 1010, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Boletos.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 90, 1090, 70);

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Terminar");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(730, 495, 160, 40);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Boton2.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton9MouseMoved(evt);
            }
        });
        jButton9.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton9MouseWheelMoved(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(730, 470, 160, 95);

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Generar PDF");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(290, 495, 160, 40);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Boton2.png"))); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton10MouseMoved(evt);
            }
        });
        jButton10.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton10MouseWheelMoved(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(290, 470, 160, 95);

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("<html>Venta realizada con éxito. Descargue el PDF para guardar la factura de la venta.<html>");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(140, 200, 660, 220);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(-600, 440, 680, 600);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1110, 450, 680, 600);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/success.gif"))); // NOI18N
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(840, 210, 240, 210);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Venta.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 170, 1090, 280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        jButton9.setIcon(new ImageIcon(getClass().getResource("/Images/Boton2.png")));
        jButton10.setIcon(new ImageIcon(getClass().getResource("/Images/Boton2.png")));

    }//GEN-LAST:event_jPanel1MouseMoved

    private void jButton9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseMoved
        // TODO add your handling code here:
        jButton9.setIcon(new ImageIcon(getClass().getResource("/Images/Boton1.png")));
    }//GEN-LAST:event_jButton9MouseMoved

    private void jButton9MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton9MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseWheelMoved

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        VentaBoletos ad;
        try {
            ad = new VentaBoletos(s, t);
            ad.show();
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseMoved
        // TODO add your handling code here:

        jButton10.setIcon(new ImageIcon(getClass().getResource("/Images/Boton1.png")));


    }//GEN-LAST:event_jButton10MouseMoved

    private void jButton10MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton10MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseWheelMoved

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String c = "";
        String e = "";
        String r = "";
        String rg = "";
        String m = "";

        String c2 = "";
        String e2 = "";
        String r2 = "";

        String c23 = "";
        String e23 = "";
        String r23 = "";
        String r24 = "";
        try {
            ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM venta where ID ='" + u + "'");
            ResultSet sr = ps.executeQuery();
            while (sr.next()) {
                c = sr.getString("cliente");
                e = sr.getString("total");
                r = sr.getString("fechaCompra");
                rg = sr.getString("hora");
                m = sr.getString("ID");
            }
            String fe2[] = r.split("-");
            r = fe2[2] + "-" + fe2[1] + "-" + fe2[0];

            ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM funcion where IDFuncion ='" + v + "'");
            ResultSet sre = ps.executeQuery();
            while (sre.next()) {
                c2 = sre.getString("sala");
                e2 = sre.getString("hora");
                r2 = sre.getString("fecha");
            }
            String fe[] = r2.split("-");
            r2 = fe[2] + "-" + fe[1] + "-" + fe[0];

            ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM pelicula where IDPelicula ='" + w + "'");
            ResultSet sree = ps.executeQuery();
            while (sree.next()) {
                c23 = sree.getString("nombre");
                e23 = sree.getString("duracion");
                r23 = sree.getString("clasificacion");
                r24 = sree.getString("genero");

            }

        } catch (SQLException ex) {

        }
        try {

            String imagePath = "src/Images/Logo.png";
            String imagePath2 = "src/Images/Fondo.png";
            Document docu = new Document(PageSize.NOTE);
            String destino = "src/Facturas/Factura" + u + ".pdf";
            PdfWriter writer = PdfWriter.getInstance(docu, new FileOutputStream(destino));
            docu.open();

            com.itextpdf.text.Image img = com.itextpdf.text.Image.getInstance(imagePath);
            img.scalePercent(22, 22);
            img.setAbsolutePosition(205, docu.getPageSize().getHeight() - img.getScaledHeight() - 10);
            writer.getDirectContentUnder().addImage(img);
            docu.add(img);

            img = com.itextpdf.text.Image.getInstance(imagePath2);
            img.scalePercent(150, 4);
            img.setAbsolutePosition(-80, docu.getPageSize().getHeight() - img.getScaledHeight() - 118);
            writer.getDirectContentUnder().addImage(img);
            docu.add(img);

            String timeStamp = new SimpleDateFormat("dd/MM/YYYY").format(Calendar.getInstance().getTime());

            Paragraph pe = new Paragraph("\n\n", FontFactory.getFont("Franklin Gothic Demi Cond", 12, Font.BOLD, new BaseColor(153, 153, 255)));
            pe.setAlignment(Element.ALIGN_CENTER);
            pe.setSpacingAfter(5f);
            docu.add(pe);
            Paragraph p = new Paragraph("Detalles de facturación\n\n", FontFactory.getFont("Franklin Gothic Demi Cond", 20, Font.BOLD, new BaseColor(51, 51, 51)));
            p.setAlignment(Element.ALIGN_CENTER);
            p.setSpacingAfter(5f);
            docu.add(p);

            p = new Paragraph("Información de la compra", FontFactory.getFont("Franklin Gothic Demi Cond", 18, Font.BOLD, new BaseColor(51, 51, 51)));

            p.setAlignment(Element.ALIGN_CENTER);
            p.setSpacingAfter(8f);
            docu.add(p);

            PdfPCell cell = new PdfPCell(new Phrase("Número de reporte"));

            PdfPTable table3 = new PdfPTable(1);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Datos del cliente", FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.BOLD, new BaseColor(255, 255, 255))));
            cell.setBackgroundColor(new BaseColor(51, 51, 51));
            cell.setBorderColor(new BaseColor(51, 51, 51));
            table3.setWidthPercentage(100);

            table3.addCell(cell);
            docu.add(table3);

            PdfPTable table2 = new PdfPTable(1);

            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Fecha de compra: " + r, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(255, 255, 255));
            cell.setBorderColor(new BaseColor(255, 255, 255));
            table2.setWidthPercentage(100);

            table2.addCell(cell);
            docu.add(table2);

            PdfPTable table4 = new PdfPTable(1);

            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Hora de la compra: " + rg, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(235, 235, 235));
            cell.setBorderColor(new BaseColor(235, 235, 235));
            table4.setWidthPercentage(100);

            table4.addCell(cell);
            docu.add(table4);

            PdfPTable table5 = new PdfPTable(1);

            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("ID de venta: " + m, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(255, 255, 255));
            cell.setBorderColor(new BaseColor(255, 255, 255));
            table5.setWidthPercentage(100);

            table5.addCell(cell);
            docu.add(table5);

            PdfPTable table6 = new PdfPTable(1);

            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Nombre del comprador: " + c, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(235, 235, 235));
            cell.setBorderColor(new BaseColor(235, 235, 235));
            table6.setWidthPercentage(100);

            table6.addCell(cell);
            docu.add(table6);

            PdfPTable table7 = new PdfPTable(1);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Información de la función", FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.BOLD, new BaseColor(255, 255, 255))));
            cell.setBackgroundColor(new BaseColor(51, 51, 51));
            cell.setBorderColor(new BaseColor(51, 51, 51));
            table7.setWidthPercentage(100);

            table7.addCell(cell);
            docu.add(table7);

            PdfPTable table8 = new PdfPTable(1);

            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Sala de la función: " + c2, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(255, 255, 255));
            cell.setBorderColor(new BaseColor(255, 255, 255));
            table8.setWidthPercentage(100);

            table8.addCell(cell);
            docu.add(table8);

            PdfPTable table9 = new PdfPTable(1);

            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Fecha de la función: " + r2, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(235, 235, 235));
            cell.setBorderColor(new BaseColor(235, 235, 235));
            table9.setWidthPercentage(100);

            table9.addCell(cell);
            docu.add(table9);

            PdfPTable table10 = new PdfPTable(1);

            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Hora de la función: " + e2, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(255, 255, 255));
            cell.setBorderColor(new BaseColor(255, 255, 255));
            table10.setWidthPercentage(100);

            table10.addCell(cell);
            docu.add(table10);

            PdfPTable table11 = new PdfPTable(1);

            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Película: " + c23, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(235, 235, 235));
            cell.setBorderColor(new BaseColor(235, 235, 235));
            table11.setWidthPercentage(100);

            table11.addCell(cell);
            docu.add(table11);

            PdfPTable table12 = new PdfPTable(1);

            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Duración: " + e23, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(255, 255, 255));
            cell.setBorderColor(new BaseColor(255, 255, 255));
            table12.setWidthPercentage(100);

            table12.addCell(cell);
            docu.add(table12);

            PdfPTable table13 = new PdfPTable(1);

            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Clasificación: " + r23, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(235, 235, 235));
            cell.setBorderColor(new BaseColor(235, 235, 235));
            table13.setWidthPercentage(100);

            table13.addCell(cell);
            docu.add(table13);

            PdfPTable table14 = new PdfPTable(1);

            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Género: " + r24, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(255, 255, 255));
            cell.setBorderColor(new BaseColor(255, 255, 255));
            table14.setWidthPercentage(100);

            table14.addCell(cell);
            docu.add(table14);

            PdfPTable table71 = new PdfPTable(1);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Boletos", FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.BOLD, new BaseColor(255, 255, 255))));
            cell.setBackgroundColor(new BaseColor(51, 51, 51));
            cell.setBorderColor(new BaseColor(51, 51, 51));
            table71.setWidthPercentage(100);

            table71.addCell(cell);
            docu.add(table71);

            PdfPTable table712 = new PdfPTable(4);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("No.", FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.BOLD, new BaseColor(255, 255, 255))));
            cell.setBackgroundColor(new BaseColor(171, 191, 229));
            cell.setBorderColor(new BaseColor(171, 191, 229));
            table712.setWidthPercentage(100);

            table712.addCell(cell);

            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Asiento", FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.BOLD, new BaseColor(255, 255, 255))));
            cell.setBackgroundColor(new BaseColor(162, 171, 242));
            cell.setBorderColor(new BaseColor(162, 171, 242));
            table712.setWidthPercentage(100);

            table712.addCell(cell);

            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Tipo", FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.BOLD, new BaseColor(255, 255, 255))));
            cell.setBackgroundColor(new BaseColor(153, 153, 255));
            cell.setBorderColor(new BaseColor(153, 153, 255));
            table712.setWidthPercentage(100);

            table712.addCell(cell);

            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("Precio", FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.BOLD, new BaseColor(255, 255, 255))));
            cell.setBackgroundColor(new BaseColor(118, 118, 196));
            cell.setBorderColor(new BaseColor(118, 118, 196));
            table712.setWidthPercentage(100);

            table712.addCell(cell);

            docu.add(table712);

            try {
                ps = (PreparedStatement) con.getConect().prepareStatement("SELECT * FROM boletos where IDVenta ='" + u + "'");
                ResultSet sr = ps.executeQuery();
                int etr = 1;
                while (sr.next()) {

                    String c22 = sr.getString("asiento");
                    String e22 = sr.getString("clasificacion");
                    String r22 = sr.getString("precio");

                    PdfPTable table15 = new PdfPTable(4);

                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    cell.setPhrase(new Phrase(String.valueOf(etr), FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
                    cell.setBackgroundColor(new BaseColor(255, 255, 255));
                    cell.setBorderColor(new BaseColor(255, 255, 255));
                    table15.setWidthPercentage(100);

                    table15.addCell(cell);
                    docu.add(table15);

                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    cell.setPhrase(new Phrase(c22, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
                    cell.setBackgroundColor(new BaseColor(255, 255, 255));
                    cell.setBorderColor(new BaseColor(255, 255, 255));
                    table15.setWidthPercentage(100);

                    table15.addCell(cell);
                    docu.add(table15);

                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    cell.setPhrase(new Phrase(e22, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
                    cell.setBackgroundColor(new BaseColor(255, 255, 255));
                    cell.setBorderColor(new BaseColor(255, 255, 255));
                    table15.setWidthPercentage(100);

                    table15.addCell(cell);
                    docu.add(table15);

                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
                    cell.setPhrase(new Phrase("$" + r22, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
                    cell.setBackgroundColor(new BaseColor(255, 255, 255));
                    cell.setBorderColor(new BaseColor(255, 255, 255));
                    table15.setWidthPercentage(100);

                    table15.addCell(cell);
                    docu.add(table15);

                    etr += 1;
                }
            } catch (SQLException ee) {

            }

            PdfPTable table15 = new PdfPTable(4);

            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("", FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(255, 255, 255));
            cell.setBorderColor(new BaseColor(255, 255, 255));
            table15.setWidthPercentage(100);

            table15.addCell(cell);

            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("", FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(255, 255, 255));
            cell.setBorderColor(new BaseColor(255, 255, 255));
            table15.setWidthPercentage(100);

            table15.addCell(cell);

            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("", FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(0, 0, 0))));
            cell.setBackgroundColor(new BaseColor(255, 255, 255));
            cell.setBorderColor(new BaseColor(255, 255, 255));
            table15.setWidthPercentage(100);

            table15.addCell(cell);

            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPhrase(new Phrase("$" + e, FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.PLAIN, new BaseColor(255, 255, 255))));
            cell.setBackgroundColor(new BaseColor(51, 51, 51));
            cell.setBorderColor(new BaseColor(51, 51, 51));
            table15.setWidthPercentage(100);

            table15.addCell(cell);

            docu.add(table15);

            

            p = new Paragraph("\n¡Gracias por su preferencia en Cine S.A!", FontFactory.getFont("Franklin Gothic Demi Cond", 16, Font.BOLD, new BaseColor(51, 51, 51)));

            p.setAlignment(Element.ALIGN_CENTER);
            p.setSpacingAfter(8f);
            docu.add(p);

            docu.close();
            jButton10.setVisible(false);
            jLabel9.setVisible(false);

            try {
//constructor of file class having file as argument  
                File file = new File(destino);
                if (!Desktop.isDesktopSupported())//check if Desktop is supported by Platform or not  
                {
                    System.out.println("not supported");
                    return;
                }
                Desktop desktop = Desktop.getDesktop();
                if (file.exists()) //checks file exists or not  
                {
                    desktop.open(file);              //opens the specified file  
                }
            } catch (Exception ex) {

            }
        } catch (FileNotFoundException | DocumentException ex) {

        } catch (IOException ex) {
            Logger.getLogger(VentaBoletos5.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaBoletos5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaBoletos5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaBoletos5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaBoletos5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaBoletos5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
